<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <Configurations>Debug;Release;Debug_Editor;Release_Editor</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Shader\**" />
    <EmbeddedResource Remove="Shader\**" />
    <None Remove="Shader\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
  </ItemGroup>

</Project>
