// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_material
{
    // From: ufbx_find_prop_texture_len(ufbx_material*, sbyte*, nuint)
    public ufbx_texture* find_prop_texture_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_prop_texture_len(
                (ufbx_material*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_prop_texture(ufbx_material*, sbyte*)
    public ufbx_texture* find_prop_texture(sbyte* name)
    {
        return Api.ufbx_find_prop_texture(
            (ufbx_material*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }
}
