// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_pose
{
    /// <summary>
    /// From: <see cref="Api.ufbx_get_bone_pose(ufbx_pose*, ufbx_node*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public ufbx_bone_pose* GetBone(ufbx_node* node)
    {
        return Api.ufbx_get_bone_pose(
            (ufbx_pose*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            node);
    }
}
