// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_scene
{
    // From: ufbx_load_memory(void*, nuint, ufbx_load_opts*, ufbx_error*)
    public static ufbx_scene* load_memory(void* data, nuint data_size, ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_memory(
            data,
            data_size,
            opts,
            error);
    }

    // From: ufbx_load_file(sbyte*, ufbx_load_opts*, ufbx_error*)
    public static ufbx_scene* load_file(sbyte* filename, ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_file(
            filename,
            opts,
            error);
    }

    // From: ufbx_load_file_len(sbyte*, nuint, ufbx_load_opts*, ufbx_error*)
    public static ufbx_scene* load_file_len(ReadOnlySpan<byte> filename, ufbx_load_opts* opts, ufbx_error* error)
    {
        fixed (byte* pfilename = filename)
        {
            return Api.ufbx_load_file_len(
                (sbyte*)pfilename,
                (nuint)filename.Length,
                opts,
                error);
        }
    }

    // From: ufbx_load_stdio(void*, ufbx_load_opts*, ufbx_error*)
    public static ufbx_scene* load_stdio(void* file, ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_stdio(
            file,
            opts,
            error);
    }

    // From: ufbx_load_stdio_prefix(void*, void*, nuint, ufbx_load_opts*, ufbx_error*)
    public static ufbx_scene* load_stdio_prefix(void* file, void* prefix, nuint prefix_size, ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_stdio_prefix(
            file,
            prefix,
            prefix_size,
            opts,
            error);
    }

    // From: ufbx_free_scene(ufbx_scene*)
    public void free()
    {
        Api.ufbx_free_scene((ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_retain_scene(ufbx_scene*)
    public void retain()
    {
        Api.ufbx_retain_scene((ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_find_element_len(ufbx_scene*, ufbx_element_type, sbyte*, nuint)
    public ufbx_element* find_element_len(ufbx_element_type type, ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_element_len(
                (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                type,
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_element(ufbx_scene*, ufbx_element_type, sbyte*)
    public ufbx_element* find_element(ufbx_element_type type, sbyte* name)
    {
        return Api.ufbx_find_element(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            type,
            name);
    }

    // From: ufbx_find_node_len(ufbx_scene*, sbyte*, nuint)
    public ufbx_node* find_node_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_node_len(
                (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_node(ufbx_scene*, sbyte*)
    public ufbx_node* find_node(sbyte* name)
    {
        return Api.ufbx_find_node(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }

    // From: ufbx_find_anim_stack_len(ufbx_scene*, sbyte*, nuint)
    public ufbx_anim_stack* find_anim_stack_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_anim_stack_len(
                (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_anim_stack(ufbx_scene*, sbyte*)
    public ufbx_anim_stack* find_anim_stack(sbyte* name)
    {
        return Api.ufbx_find_anim_stack(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }

    // From: ufbx_find_material_len(ufbx_scene*, sbyte*, nuint)
    public ufbx_material* find_material_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_material_len(
                (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_material(ufbx_scene*, sbyte*)
    public ufbx_material* find_material(sbyte* name)
    {
        return Api.ufbx_find_material(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }

    // From: ufbx_evaluate_scene(ufbx_scene*, ufbx_anim*, double, ufbx_evaluate_opts*, ufbx_error*)
    public ufbx_scene* evaluate(ufbx_anim* anim, double time, ufbx_evaluate_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_evaluate_scene(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            anim,
            time,
            opts,
            error);
    }

    // From: ufbx_create_anim(ufbx_scene*, ufbx_anim_opts*, ufbx_error*)
    public ufbx_anim* create_anim(ufbx_anim_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_create_anim(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            opts,
            error);
    }

    // From: ufbx_bake_anim(ufbx_scene*, ufbx_anim*, ufbx_bake_opts*, ufbx_error*)
    public ufbx_baked_anim* bake_anim(ufbx_anim* anim, ufbx_bake_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_bake_anim(
            (ufbx_scene*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            anim,
            opts,
            error);
    }
}
