// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_blend_deformer
{
    // From: ufbx_get_blend_vertex_offset(ufbx_blend_deformer*, nuint)
    public Misaki.HighPerformance.Mathematics.float3 get_blend_vertex_offset(nuint vertex)
    {
        return Api.ufbx_get_blend_vertex_offset(
            (ufbx_blend_deformer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertex);
    }

    // From: ufbx_add_blend_vertex_offsets(ufbx_blend_deformer*, Misaki.HighPerformance.Mathematics.float3*, nuint, float)
    public void add_blend_vertex_offsets(Misaki.HighPerformance.Mathematics.float3* vertices, nuint num_vertices, float weight)
    {
        Api.ufbx_add_blend_vertex_offsets(
            (ufbx_blend_deformer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertices,
            num_vertices,
            weight);
    }
}
