// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_cache_frame
{
    // From: ufbx_read_geometry_cache_real(ufbx_cache_frame*, float*, nuint, ufbx_geometry_cache_data_opts*)
    public nuint read_geometry_cache_real(float* data, nuint num_data, ufbx_geometry_cache_data_opts* opts)
    {
        return Api.ufbx_read_geometry_cache_real(
            (ufbx_cache_frame*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            num_data,
            opts);
    }

    // From: ufbx_read_geometry_cache_vec3(ufbx_cache_frame*, Misaki.HighPerformance.Mathematics.float3*, nuint, ufbx_geometry_cache_data_opts*)
    public nuint read_geometry_cache_vec3(Misaki.HighPerformance.Mathematics.float3* data, nuint num_data, ufbx_geometry_cache_data_opts* opts)
    {
        return Api.ufbx_read_geometry_cache_vec3(
            (ufbx_cache_frame*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            num_data,
            opts);
    }
}
