// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_cache_channel
{
    // From: ufbx_sample_geometry_cache_real(ufbx_cache_channel*, double, float*, nuint, ufbx_geometry_cache_data_opts*)
    public nuint sample_geometry_cache_real(double time, float* data, nuint num_data, ufbx_geometry_cache_data_opts* opts)
    {
        return Api.ufbx_sample_geometry_cache_real(
            (ufbx_cache_channel*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            data,
            num_data,
            opts);
    }

    // From: ufbx_sample_geometry_cache_vec3(ufbx_cache_channel*, double, Misaki.HighPerformance.Mathematics.float3*, nuint, ufbx_geometry_cache_data_opts*)
    public nuint sample_geometry_cache_vec3(double time, Misaki.HighPerformance.Mathematics.float3* data, nuint num_data, ufbx_geometry_cache_data_opts* opts)
    {
        return Api.ufbx_sample_geometry_cache_vec3(
            (ufbx_cache_channel*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            data,
            num_data,
            opts);
    }
}
