// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_pose
{
    // From: ufbx_get_bone_pose(ufbx_pose*, ufbx_node*)
    public ufbx_bone_pose* get_bone(ufbx_node* node)
    {
        return Api.ufbx_get_bone_pose(
            (ufbx_pose*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            node);
    }
}
