// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_panic
{
    // From: ufbx_catch_get_skin_vertex_matrix(ufbx_panic*, ufbx_skin_deformer*, nuint, Misaki.HighPerformance.Mathematics.float3x4*)
    public Misaki.HighPerformance.Mathematics.float3x4 catch_get_skin_vertex_matrix(ufbx_skin_deformer* skin, nuint vertex, Misaki.HighPerformance.Mathematics.float3x4* fallback)
    {
        return Api.ufbx_catch_get_skin_vertex_matrix(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            skin,
            vertex,
            fallback);
    }

    // From: ufbx_catch_triangulate_face(ufbx_panic*, uint*, nuint, ufbx_mesh*, ufbx_face)
    public uint catch_triangulate_face(uint* indices, nuint num_indices, ufbx_mesh* mesh, ufbx_face face)
    {
        return Api.ufbx_catch_triangulate_face(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            indices,
            num_indices,
            mesh,
            face);
    }

    // From: ufbx_catch_compute_topology(ufbx_panic*, ufbx_mesh*, ufbx_topo_edge*, nuint)
    public void catch_compute_topology(ufbx_mesh* mesh, ufbx_topo_edge* topo, nuint num_topo)
    {
        Api.ufbx_catch_compute_topology(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mesh,
            topo,
            num_topo);
    }

    // From: ufbx_catch_topo_next_vertex_edge(ufbx_panic*, ufbx_topo_edge*, nuint, uint)
    public uint catch_topo_next_vertex_edge(ufbx_topo_edge* topo, nuint num_topo, uint index)
    {
        return Api.ufbx_catch_topo_next_vertex_edge(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            topo,
            num_topo,
            index);
    }

    // From: ufbx_catch_topo_prev_vertex_edge(ufbx_panic*, ufbx_topo_edge*, nuint, uint)
    public uint catch_topo_prev_vertex_edge(ufbx_topo_edge* topo, nuint num_topo, uint index)
    {
        return Api.ufbx_catch_topo_prev_vertex_edge(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            topo,
            num_topo,
            index);
    }

    // From: ufbx_catch_get_weighted_face_normal(ufbx_panic*, ufbx_vertex_vec3*, ufbx_face)
    public Misaki.HighPerformance.Mathematics.float3 catch_get_weighted_face_normal(ufbx_vertex_vec3* positions, ufbx_face face)
    {
        return Api.ufbx_catch_get_weighted_face_normal(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            positions,
            face);
    }

    // From: ufbx_catch_generate_normal_mapping(ufbx_panic*, ufbx_mesh*, ufbx_topo_edge*, nuint, uint*, nuint, bool)
    public nuint catch_generate_normal_mapping(ufbx_mesh* mesh, ufbx_topo_edge* topo, nuint num_topo, uint* normal_indices, nuint num_normal_indices, bool assume_smooth)
    {
        return Api.ufbx_catch_generate_normal_mapping(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mesh,
            topo,
            num_topo,
            normal_indices,
            num_normal_indices,
            assume_smooth);
    }

    // From: ufbx_catch_compute_normals(ufbx_panic*, ufbx_mesh*, ufbx_vertex_vec3*, uint*, nuint, Misaki.HighPerformance.Mathematics.float3*, nuint)
    public void catch_compute_normals(ufbx_mesh* mesh, ufbx_vertex_vec3* positions, uint* normal_indices, nuint num_normal_indices, Misaki.HighPerformance.Mathematics.float3* normals, nuint num_normals)
    {
        Api.ufbx_catch_compute_normals(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mesh,
            positions,
            normal_indices,
            num_normal_indices,
            normals,
            num_normals);
    }

    // From: ufbx_catch_get_vertex_real(ufbx_panic*, ufbx_vertex_real*, nuint)
    public float catch_get_vertex_real(ufbx_vertex_real* v, nuint index)
    {
        return Api.ufbx_catch_get_vertex_real(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            v,
            index);
    }

    // From: ufbx_catch_get_vertex_vec2(ufbx_panic*, ufbx_vertex_vec2*, nuint)
    public Misaki.HighPerformance.Mathematics.float2 catch_get_vertex_vec2(ufbx_vertex_vec2* v, nuint index)
    {
        return Api.ufbx_catch_get_vertex_vec2(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            v,
            index);
    }

    // From: ufbx_catch_get_vertex_vec3(ufbx_panic*, ufbx_vertex_vec3*, nuint)
    public Misaki.HighPerformance.Mathematics.float3 catch_get_vertex_vec3(ufbx_vertex_vec3* v, nuint index)
    {
        return Api.ufbx_catch_get_vertex_vec3(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            v,
            index);
    }

    // From: ufbx_catch_get_vertex_vec4(ufbx_panic*, ufbx_vertex_vec4*, nuint)
    public Misaki.HighPerformance.Mathematics.float4 catch_get_vertex_vec4(ufbx_vertex_vec4* v, nuint index)
    {
        return Api.ufbx_catch_get_vertex_vec4(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            v,
            index);
    }

    // From: ufbx_catch_get_vertex_w_vec3(ufbx_panic*, ufbx_vertex_vec3*, nuint)
    public float catch_get_vertex_w_vec3(ufbx_vertex_vec3* v, nuint index)
    {
        return Api.ufbx_catch_get_vertex_w_vec3(
            (ufbx_panic*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            v,
            index);
    }
}
