// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_nurbs_surface
{
    // From: ufbx_evaluate_nurbs_surface(ufbx_nurbs_surface*, float, float)
    public ufbx_surface_point evaluate(float u, float v)
    {
        return Api.ufbx_evaluate_nurbs_surface(
            (ufbx_nurbs_surface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            u,
            v);
    }

    // From: ufbx_tessellate_nurbs_surface(ufbx_nurbs_surface*, ufbx_tessellate_surface_opts*, ufbx_error*)
    public ufbx_mesh* tessellate(ufbx_tessellate_surface_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_tessellate_nurbs_surface(
            (ufbx_nurbs_surface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            opts,
            error);
    }
}
