// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_line_curve
{
    // From: ufbx_free_line_curve(ufbx_line_curve*)
    public void free()
    {
        Api.ufbx_free_line_curve((ufbx_line_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_retain_line_curve(ufbx_line_curve*)
    public void retain()
    {
        Api.ufbx_retain_line_curve((ufbx_line_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
