// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_vertex_vec3
{
    // From: ufbx_get_weighted_face_normal(ufbx_vertex_vec3*, ufbx_face)
    public Misaki.HighPerformance.Mathematics.float3 get_weighted_face_normal(ufbx_face face)
    {
        return Api.ufbx_get_weighted_face_normal(
            (ufbx_vertex_vec3*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            face);
    }
}
