// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_shader
{
    // From: ufbx_find_shader_prop_len(ufbx_shader*, sbyte*, nuint)
    public ufbx_string find_shader_prop_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_shader_prop_len(
                (ufbx_shader*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_shader_prop(ufbx_shader*, sbyte*)
    public ufbx_string find_shader_prop(sbyte* name)
    {
        return Api.ufbx_find_shader_prop(
            (ufbx_shader*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }

    // From: ufbx_find_shader_prop_bindings_len(ufbx_shader*, sbyte*, nuint)
    public ufbx_shader_prop_binding_list find_shader_prop_bindings_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_shader_prop_bindings_len(
                (ufbx_shader*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_shader_prop_bindings(ufbx_shader*, sbyte*)
    public ufbx_shader_prop_binding_list find_shader_prop_bindings(sbyte* name)
    {
        return Api.ufbx_find_shader_prop_bindings(
            (ufbx_shader*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }
}
