// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_stream
{
    // From: ufbx_load_stream(ufbx_stream*, ufbx_load_opts*, ufbx_error*)
    public ufbx_scene* load(ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_stream(
            (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            opts,
            error);
    }

    // From: ufbx_load_stream_prefix(ufbx_stream*, void*, nuint, ufbx_load_opts*, ufbx_error*)
    public ufbx_scene* load_stream_prefix(void* prefix, nuint prefix_size, ufbx_load_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_stream_prefix(
            (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            prefix,
            prefix_size,
            opts,
            error);
    }

    // From: ufbx_open_file(ufbx_stream*, sbyte*, nuint, ufbx_open_file_opts*, ufbx_error*)
    public bool open_file(ReadOnlySpan<byte> path, ufbx_open_file_opts* opts, ufbx_error* error)
    {
        fixed (byte* ppath = path)
        {
            return Api.ufbx_open_file(
                (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)ppath,
                (nuint)path.Length,
                opts,
                error);
        }
    }

    // From: ufbx_open_file_ctx(ufbx_stream*, nuint, sbyte*, nuint, ufbx_open_file_opts*, ufbx_error*)
    public bool open_file_ctx(nuint ctx, ReadOnlySpan<byte> path, ufbx_open_file_opts* opts, ufbx_error* error)
    {
        fixed (byte* ppath = path)
        {
            return Api.ufbx_open_file_ctx(
                (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                ctx,
                (sbyte*)ppath,
                (nuint)path.Length,
                opts,
                error);
        }
    }

    // From: ufbx_open_memory(ufbx_stream*, void*, nuint, ufbx_open_memory_opts*, ufbx_error*)
    public bool open_memory(void* data, nuint data_size, ufbx_open_memory_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_open_memory(
            (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            data_size,
            opts,
            error);
    }

    // From: ufbx_open_memory_ctx(ufbx_stream*, nuint, void*, nuint, ufbx_open_memory_opts*, ufbx_error*)
    public bool open_memory_ctx(nuint ctx, void* data, nuint data_size, ufbx_open_memory_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_open_memory_ctx(
            (ufbx_stream*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            ctx,
            data,
            data_size,
            opts,
            error);
    }
}
