// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_topo_edge
{
    /// <summary>
    /// From: <see cref="Api.ufbx_topo_next_vertex_edge(ufbx_topo_edge*, nuint, uint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public uint TopoNextVertexEdge(nuint num_topo, uint index)
    {
        return Api.ufbx_topo_next_vertex_edge(
            (ufbx_topo_edge*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            num_topo,
            index);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_topo_prev_vertex_edge(ufbx_topo_edge*, nuint, uint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public uint TopoPrevVertexEdge(nuint num_topo, uint index)
    {
        return Api.ufbx_topo_prev_vertex_edge(
            (ufbx_topo_edge*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            num_topo,
            index);
    }
}
