// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_blend_deformer
{
    /// <summary>
    /// From: <see cref="Api.ufbx_get_blend_vertex_offset(ufbx_blend_deformer*, nuint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public ufbx_vec3 GetBlendVertexOffset(nuint vertex)
    {
        return Api.ufbx_get_blend_vertex_offset(
            (ufbx_blend_deformer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertex);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_add_blend_vertex_offsets(ufbx_blend_deformer*, ufbx_vec3*, nuint, float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void AddBlendVertexOffsets(ReadOnlySpan<ufbx_vec3> vertices, float weight)
    {
        fixed (ufbx_vec3* pvertices = vertices)
        {
            Api.ufbx_add_blend_vertex_offsets(
                (ufbx_blend_deformer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (ufbx_vec3*)pvertices,
                (nuint)vertices.Length,
                weight);
        }
    }
}
