// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_element
{
    // From: ufbx_get_prop_element(ufbx_element*, ufbx_prop*, ufbx_element_type)
    public ufbx_element* get_prop(ufbx_prop* prop, ufbx_element_type type)
    {
        return Api.ufbx_get_prop_element(
            (ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            prop,
            type);
    }

    // From: ufbx_find_prop_element_len(ufbx_element*, sbyte*, nuint, ufbx_element_type)
    public ufbx_element* find_prop_element_len(ReadOnlySpan<byte> name, ufbx_element_type type)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_prop_element_len(
                (ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length,
                type);
        }
    }

    // From: ufbx_find_prop_element(ufbx_element*, sbyte*, ufbx_element_type)
    public ufbx_element* find_prop(sbyte* name, ufbx_element_type type)
    {
        return Api.ufbx_find_prop_element(
            (ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name,
            type);
    }

    // From: ufbx_as_unknown(ufbx_element*)
    public ufbx_unknown* as_unknown()
    {
        return Api.ufbx_as_unknown((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_node(ufbx_element*)
    public ufbx_node* as_node()
    {
        return Api.ufbx_as_node((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_mesh(ufbx_element*)
    public ufbx_mesh* as_mesh()
    {
        return Api.ufbx_as_mesh((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_light(ufbx_element*)
    public ufbx_light* as_light()
    {
        return Api.ufbx_as_light((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_camera(ufbx_element*)
    public ufbx_camera* as_camera()
    {
        return Api.ufbx_as_camera((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_bone(ufbx_element*)
    public ufbx_bone* as_bone()
    {
        return Api.ufbx_as_bone((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_empty(ufbx_element*)
    public ufbx_empty* as_empty()
    {
        return Api.ufbx_as_empty((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_line_curve(ufbx_element*)
    public ufbx_line_curve* as_line_curve()
    {
        return Api.ufbx_as_line_curve((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_nurbs_curve(ufbx_element*)
    public ufbx_nurbs_curve* as_nurbs_curve()
    {
        return Api.ufbx_as_nurbs_curve((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_nurbs_surface(ufbx_element*)
    public ufbx_nurbs_surface* as_nurbs_surface()
    {
        return Api.ufbx_as_nurbs_surface((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_nurbs_trim_surface(ufbx_element*)
    public ufbx_nurbs_trim_surface* as_nurbs_trim_surface()
    {
        return Api.ufbx_as_nurbs_trim_surface((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_nurbs_trim_boundary(ufbx_element*)
    public ufbx_nurbs_trim_boundary* as_nurbs_trim_boundary()
    {
        return Api.ufbx_as_nurbs_trim_boundary((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_procedural_geometry(ufbx_element*)
    public ufbx_procedural_geometry* as_procedural_geometry()
    {
        return Api.ufbx_as_procedural_geometry((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_stereo_camera(ufbx_element*)
    public ufbx_stereo_camera* as_stereo_camera()
    {
        return Api.ufbx_as_stereo_camera((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_camera_switcher(ufbx_element*)
    public ufbx_camera_switcher* as_camera_switcher()
    {
        return Api.ufbx_as_camera_switcher((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_marker(ufbx_element*)
    public ufbx_marker* as_marker()
    {
        return Api.ufbx_as_marker((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_lod_group(ufbx_element*)
    public ufbx_lod_group* as_lod_group()
    {
        return Api.ufbx_as_lod_group((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_skin_deformer(ufbx_element*)
    public ufbx_skin_deformer* as_skin_deformer()
    {
        return Api.ufbx_as_skin_deformer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_skin_cluster(ufbx_element*)
    public ufbx_skin_cluster* as_skin_cluster()
    {
        return Api.ufbx_as_skin_cluster((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_blend_deformer(ufbx_element*)
    public ufbx_blend_deformer* as_blend_deformer()
    {
        return Api.ufbx_as_blend_deformer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_blend_channel(ufbx_element*)
    public ufbx_blend_channel* as_blend_channel()
    {
        return Api.ufbx_as_blend_channel((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_blend_shape(ufbx_element*)
    public ufbx_blend_shape* as_blend_shape()
    {
        return Api.ufbx_as_blend_shape((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_cache_deformer(ufbx_element*)
    public ufbx_cache_deformer* as_cache_deformer()
    {
        return Api.ufbx_as_cache_deformer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_cache_file(ufbx_element*)
    public ufbx_cache_file* as_cache_file()
    {
        return Api.ufbx_as_cache_file((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_material(ufbx_element*)
    public ufbx_material* as_material()
    {
        return Api.ufbx_as_material((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_texture(ufbx_element*)
    public ufbx_texture* as_texture()
    {
        return Api.ufbx_as_texture((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_video(ufbx_element*)
    public ufbx_video* as_video()
    {
        return Api.ufbx_as_video((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_shader(ufbx_element*)
    public ufbx_shader* as_shader()
    {
        return Api.ufbx_as_shader((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_shader_binding(ufbx_element*)
    public ufbx_shader_binding* as_shader_binding()
    {
        return Api.ufbx_as_shader_binding((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_anim_stack(ufbx_element*)
    public ufbx_anim_stack* as_anim_stack()
    {
        return Api.ufbx_as_anim_stack((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_anim_layer(ufbx_element*)
    public ufbx_anim_layer* as_anim_layer()
    {
        return Api.ufbx_as_anim_layer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_anim_value(ufbx_element*)
    public ufbx_anim_value* as_anim_value()
    {
        return Api.ufbx_as_anim_value((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_anim_curve(ufbx_element*)
    public ufbx_anim_curve* as_anim_curve()
    {
        return Api.ufbx_as_anim_curve((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_display_layer(ufbx_element*)
    public ufbx_display_layer* as_display_layer()
    {
        return Api.ufbx_as_display_layer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_selection_set(ufbx_element*)
    public ufbx_selection_set* as_selection_set()
    {
        return Api.ufbx_as_selection_set((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_selection_node(ufbx_element*)
    public ufbx_selection_node* as_selection_node()
    {
        return Api.ufbx_as_selection_node((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_character(ufbx_element*)
    public ufbx_character* as_character()
    {
        return Api.ufbx_as_character((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_constraint(ufbx_element*)
    public ufbx_constraint* as_constraint()
    {
        return Api.ufbx_as_constraint((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_audio_layer(ufbx_element*)
    public ufbx_audio_layer* as_audio_layer()
    {
        return Api.ufbx_as_audio_layer((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_audio_clip(ufbx_element*)
    public ufbx_audio_clip* as_audio_clip()
    {
        return Api.ufbx_as_audio_clip((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_pose(ufbx_element*)
    public ufbx_pose* as_pose()
    {
        return Api.ufbx_as_pose((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_as_metadata_object(ufbx_element*)
    public ufbx_metadata_object* as_metadata_object()
    {
        return Api.ufbx_as_metadata_object((ufbx_element*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
