// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_anim_layer
{
    // From: ufbx_find_anim_prop_len(ufbx_anim_layer*, ufbx_element*, sbyte*, nuint)
    public ufbx_anim_prop* find_anim_prop_len(ufbx_element* element, ReadOnlySpan<byte> prop)
    {
        fixed (byte* pprop = prop)
        {
            return Api.ufbx_find_anim_prop_len(
                (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                element,
                (sbyte*)pprop,
                (nuint)prop.Length);
        }
    }

    // From: ufbx_find_anim_prop(ufbx_anim_layer*, ufbx_element*, sbyte*)
    public ufbx_anim_prop* find_anim_prop(ufbx_element* element, sbyte* prop)
    {
        return Api.ufbx_find_anim_prop(
            (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element,
            prop);
    }

    // From: ufbx_find_anim_props(ufbx_anim_layer*, ufbx_element*)
    public ufbx_anim_prop_list find_anim_props(ufbx_element* element)
    {
        return Api.ufbx_find_anim_props(
            (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element);
    }
}
