// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_blend_shape
{
    /// <summary>
    /// From: <see cref="Api.ufbx_get_blend_shape_offset_index(ufbx_blend_shape*, nuint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public uint GetOffsetIndex(nuint vertex)
    {
        return Api.ufbx_get_blend_shape_offset_index(
            (ufbx_blend_shape*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertex);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_get_blend_shape_vertex_offset(ufbx_blend_shape*, nuint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public Misaki.HighPerformance.Mathematics.float3 GetVertexOffset(nuint vertex)
    {
        return Api.ufbx_get_blend_shape_vertex_offset(
            (ufbx_blend_shape*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertex);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_add_blend_shape_vertex_offsets(ufbx_blend_shape*, Misaki.HighPerformance.Mathematics.float3*, nuint, float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void AddVertexOffsets(Misaki.HighPerformance.Mathematics.float3* vertices, nuint num_vertices, float weight)
    {
        Api.ufbx_add_blend_shape_vertex_offsets(
            (ufbx_blend_shape*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            vertices,
            num_vertices,
            weight);
    }
}
