// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_anim_value
{
    // From: ufbx_evaluate_anim_value_real(ufbx_anim_value*, double)
    public float evaluate_anim_value_real(double time)
    {
        return Api.ufbx_evaluate_anim_value_real(
            (ufbx_anim_value*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time);
    }

    // From: ufbx_evaluate_anim_value_vec3(ufbx_anim_value*, double)
    public Misaki.HighPerformance.Mathematics.float3 evaluate_anim_value_vec3(double time)
    {
        return Api.ufbx_evaluate_anim_value_vec3(
            (ufbx_anim_value*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time);
    }

    // From: ufbx_evaluate_anim_value_real_flags(ufbx_anim_value*, double, uint)
    public float evaluate_anim_value_real_flags(double time, uint flags)
    {
        return Api.ufbx_evaluate_anim_value_real_flags(
            (ufbx_anim_value*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            flags);
    }

    // From: ufbx_evaluate_anim_value_vec3_flags(ufbx_anim_value*, double, uint)
    public Misaki.HighPerformance.Mathematics.float3 evaluate_anim_value_vec3_flags(double time, uint flags)
    {
        return Api.ufbx_evaluate_anim_value_vec3_flags(
            (ufbx_anim_value*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            flags);
    }
}
