// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_geometry_cache
{
    // From: ufbx_load_geometry_cache(sbyte*, ufbx_geometry_cache_opts*, ufbx_error*)
    public static ufbx_geometry_cache* load(sbyte* filename, ufbx_geometry_cache_opts* opts, ufbx_error* error)
    {
        return Api.ufbx_load_geometry_cache(
            filename,
            opts,
            error);
    }

    // From: ufbx_load_geometry_cache_len(sbyte*, nuint, ufbx_geometry_cache_opts*, ufbx_error*)
    public static ufbx_geometry_cache* load_geometry_cache_len(ReadOnlySpan<byte> filename, ufbx_geometry_cache_opts* opts, ufbx_error* error)
    {
        fixed (byte* pfilename = filename)
        {
            return Api.ufbx_load_geometry_cache_len(
                (sbyte*)pfilename,
                (nuint)filename.Length,
                opts,
                error);
        }
    }

    // From: ufbx_free_geometry_cache(ufbx_geometry_cache*)
    public void free()
    {
        Api.ufbx_free_geometry_cache((ufbx_geometry_cache*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_retain_geometry_cache(ufbx_geometry_cache*)
    public void retain()
    {
        Api.ufbx_retain_geometry_cache((ufbx_geometry_cache*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
