// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_baked_anim
{
    // From: ufbx_retain_baked_anim(ufbx_baked_anim*)
    public void retain()
    {
        Api.ufbx_retain_baked_anim((ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_free_baked_anim(ufbx_baked_anim*)
    public void free()
    {
        Api.ufbx_free_baked_anim((ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_find_baked_node_by_typed_id(ufbx_baked_anim*, uint)
    public ufbx_baked_node* find_baked_node_by_typed_id(uint typed_id)
    {
        return Api.ufbx_find_baked_node_by_typed_id(
            (ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            typed_id);
    }

    // From: ufbx_find_baked_node(ufbx_baked_anim*, ufbx_node*)
    public ufbx_baked_node* find_baked_node(ufbx_node* node)
    {
        return Api.ufbx_find_baked_node(
            (ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            node);
    }

    // From: ufbx_find_baked_element_by_element_id(ufbx_baked_anim*, uint)
    public ufbx_baked_element* find_baked_element_by_element_id(uint element_id)
    {
        return Api.ufbx_find_baked_element_by_element_id(
            (ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element_id);
    }

    // From: ufbx_find_baked_element(ufbx_baked_anim*, ufbx_element*)
    public ufbx_baked_element* find_baked_element(ufbx_element* element)
    {
        return Api.ufbx_find_baked_element(
            (ufbx_baked_anim*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element);
    }
}
