// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_nurbs_basis
{
    // From: ufbx_evaluate_nurbs_basis(ufbx_nurbs_basis*, float, float*, nuint, float*, nuint)
    public nuint evaluate(float u, float* weights, nuint num_weights, float* derivatives, nuint num_derivatives)
    {
        return Api.ufbx_evaluate_nurbs_basis(
            (ufbx_nurbs_basis*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            u,
            weights,
            num_weights,
            derivatives,
            num_derivatives);
    }
}
