// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_dom_node
{
    // From: ufbx_dom_find_len(ufbx_dom_node*, sbyte*, nuint)
    public ufbx_dom_node* dom_find_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_dom_find_len(
                (ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_dom_find(ufbx_dom_node*, sbyte*)
    public ufbx_dom_node* dom_find(sbyte* name)
    {
        return Api.ufbx_dom_find(
            (ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }

    // From: ufbx_dom_is_array(ufbx_dom_node*)
    public bool dom_is_array()
    {
        return Api.ufbx_dom_is_array((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_array_size(ufbx_dom_node*)
    public nuint dom_array_size()
    {
        return Api.ufbx_dom_array_size((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_int32_list(ufbx_dom_node*)
    public ufbx_int32_list dom_as_int32_list()
    {
        return Api.ufbx_dom_as_int32_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_int64_list(ufbx_dom_node*)
    public ufbx_int64_list dom_as_int64_list()
    {
        return Api.ufbx_dom_as_int64_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_float_list(ufbx_dom_node*)
    public ufbx_float_list dom_as_float_list()
    {
        return Api.ufbx_dom_as_float_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_double_list(ufbx_dom_node*)
    public ufbx_double_list dom_as_double_list()
    {
        return Api.ufbx_dom_as_double_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_real_list(ufbx_dom_node*)
    public ufbx_real_list dom_as_real_list()
    {
        return Api.ufbx_dom_as_real_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: ufbx_dom_as_blob_list(ufbx_dom_node*)
    public ufbx_blob_list dom_as_blob_list()
    {
        return Api.ufbx_dom_as_blob_list((ufbx_dom_node*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
