// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_anim_curve
{
    /// <summary>
    /// From: <see cref="Api.ufbx_evaluate_curve(ufbx_anim_curve*, double, float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float EvaluateCurve(double time, float default_value)
    {
        return Api.ufbx_evaluate_curve(
            (ufbx_anim_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            default_value);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_evaluate_curve_flags(ufbx_anim_curve*, double, float, uint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public float EvaluateCurveFlags(double time, float default_value, uint flags)
    {
        return Api.ufbx_evaluate_curve_flags(
            (ufbx_anim_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            default_value,
            flags);
    }
}
