// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_anim_layer
{
    /// <summary>
    /// From: <see cref="Api.ufbx_find_anim_prop_len(ufbx_anim_layer*, ufbx_element*, sbyte*, nuint)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public ufbx_anim_prop* FindAnimPropLen(ufbx_element* element, ReadOnlySpan<byte> prop)
    {
        fixed (byte* pprop = prop)
        {
            return Api.ufbx_find_anim_prop_len(
                (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                element,
                (sbyte*)pprop,
                (nuint)prop.Length);
        }
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_find_anim_prop(ufbx_anim_layer*, ufbx_element*, sbyte*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public ufbx_anim_prop* FindAnimProp(ufbx_element* element, sbyte* prop)
    {
        return Api.ufbx_find_anim_prop(
            (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element,
            prop);
    }

    /// <summary>
    /// From: <see cref="Api.ufbx_find_anim_props(ufbx_anim_layer*, ufbx_element*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public ufbx_anim_prop_list FindAnimProps(ufbx_element* element)
    {
        return Api.ufbx_find_anim_props(
            (ufbx_anim_layer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            element);
    }
}
