// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_topo_edge
{
    // From: ufbx_topo_next_vertex_edge(ufbx_topo_edge*, nuint, uint)
    public uint topo_next_vertex_edge(nuint num_topo, uint index)
    {
        return Api.ufbx_topo_next_vertex_edge(
            (ufbx_topo_edge*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            num_topo,
            index);
    }

    // From: ufbx_topo_prev_vertex_edge(ufbx_topo_edge*, nuint, uint)
    public uint topo_prev_vertex_edge(nuint num_topo, uint index)
    {
        return Api.ufbx_topo_prev_vertex_edge(
            (ufbx_topo_edge*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            num_topo,
            index);
    }
}
