// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_transform
{
    // From: ufbx_transform_to_matrix(ufbx_transform*)
    public Misaki.HighPerformance.Mathematics.float3x4 to_matrix()
    {
        return Api.ufbx_transform_to_matrix((ufbx_transform*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
