// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_shader_texture
{
    // From: ufbx_find_shader_texture_input_len(ufbx_shader_texture*, sbyte*, nuint)
    public ufbx_shader_texture_input* find_shader_texture_input_len(ReadOnlySpan<byte> name)
    {
        fixed (byte* pname = name)
        {
            return Api.ufbx_find_shader_texture_input_len(
                (ufbx_shader_texture*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pname,
                (nuint)name.Length);
        }
    }

    // From: ufbx_find_shader_texture_input(ufbx_shader_texture*, sbyte*)
    public ufbx_shader_texture_input* find_shader_texture_input(sbyte* name)
    {
        return Api.ufbx_find_shader_texture_input(
            (ufbx_shader_texture*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            name);
    }
}
