// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace Ghost.Ufbx;

public unsafe partial struct ufbx_anim_curve
{
    // From: ufbx_evaluate_curve(ufbx_anim_curve*, double, float)
    public float evaluate_curve(double time, float default_value)
    {
        return Api.ufbx_evaluate_curve(
            (ufbx_anim_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            default_value);
    }

    // From: ufbx_evaluate_curve_flags(ufbx_anim_curve*, double, float, uint)
    public float evaluate_curve_flags(double time, float default_value, uint flags)
    {
        return Api.ufbx_evaluate_curve_flags(
            (ufbx_anim_curve*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            time,
            default_value,
            flags);
    }
}
