<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>True</PublishAot>
    <Configurations>Debug;Release;Debug_Editor;Release_Editor</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Editor\Ghost.DSL\Ghost.DSL.csproj" />
  </ItemGroup>

</Project>
