// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttCompressionOptions : System.IDisposable
{
    // From: nvttCreateCompressionOptions()
    public static NvttCompressionOptions* Create()
    {
        return Api.nvttCreateCompressionOptions();
    }

    // From: nvttDestroyCompressionOptions(NvttCompressionOptions*)
    public void Dispose()
    {
        Api.nvttDestroyCompressionOptions((NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttResetCompressionOptions(NvttCompressionOptions*)
    public void Reset()
    {
        Api.nvttResetCompressionOptions((NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSetCompressionOptionsFormat(NvttCompressionOptions*, NvttFormat)
    public void SetFormat(NvttFormat format)
    {
        Api.nvttSetCompressionOptionsFormat(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            format);
    }

    // From: nvttSetCompressionOptionsQuality(NvttCompressionOptions*, NvttQuality)
    public void SetQuality(NvttQuality quality)
    {
        Api.nvttSetCompressionOptionsQuality(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            quality);
    }

    // From: nvttSetCompressionOptionsColorWeights(NvttCompressionOptions*, float, float, float, float)
    public void SetColorWeights(float red, float green, float blue, float alpha)
    {
        Api.nvttSetCompressionOptionsColorWeights(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            red,
            green,
            blue,
            alpha);
    }

    // From: nvttSetCompressionOptionsPixelFormat(NvttCompressionOptions*, uint, uint, uint, uint, uint)
    public void SetPixelFormat(uint bitcount, uint rmask, uint gmask, uint bmask, uint amask)
    {
        Api.nvttSetCompressionOptionsPixelFormat(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            bitcount,
            rmask,
            gmask,
            bmask,
            amask);
    }

    // From: nvttSetCompressionOptionsPixelType(NvttCompressionOptions*, NvttPixelType)
    public void SetPixelType(NvttPixelType pixelType)
    {
        Api.nvttSetCompressionOptionsPixelType(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            pixelType);
    }

    // From: nvttSetCompressionOptionsPitchAlignment(NvttCompressionOptions*, int)
    public void SetPitchAlignment(int pitchAlignment)
    {
        Api.nvttSetCompressionOptionsPitchAlignment(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            pitchAlignment);
    }

    // From: nvttSetCompressionOptionsQuantization(NvttCompressionOptions*, NvttBoolean, NvttBoolean, NvttBoolean, int)
    public void SetQuantization(NvttBoolean colorDithering, NvttBoolean alphaDithering, NvttBoolean binaryAlpha, int alphaThreshold)
    {
        Api.nvttSetCompressionOptionsQuantization(
            (NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            colorDithering,
            alphaDithering,
            binaryAlpha,
            alphaThreshold);
    }

    // From: nvttGetCompressionOptionsD3D9Format(NvttCompressionOptions*)
    public uint GetD3D9Format()
    {
        return Api.nvttGetCompressionOptionsD3D9Format((NvttCompressionOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }
}
