// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttBatchList : System.IDisposable
{
    // From: nvttCreateBatchList()
    public static NvttBatchList* Create()
    {
        return Api.nvttCreateBatchList();
    }

    // From: nvttDestroyBatchList(NvttBatchList*)
    public void Dispose()
    {
        Api.nvttDestroyBatchList((NvttBatchList*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttBatchListClear(NvttBatchList*)
    public void Clear()
    {
        Api.nvttBatchListClear((NvttBatchList*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttBatchListAppend(NvttBatchList*, NvttSurface*, int, int, NvttOutputOptions*)
    public void Append(NvttSurface* pImg, int face, int mipmap, NvttOutputOptions* outputOptions)
    {
        Api.nvttBatchListAppend(
            (NvttBatchList*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            pImg,
            face,
            mipmap,
            outputOptions);
    }

    // From: nvttBatchListGetSize(NvttBatchList*)
    public uint GetSize()
    {
        return Api.nvttBatchListGetSize((NvttBatchList*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttBatchListGetItem(NvttBatchList*, uint, NvttSurface**, int*, int*, NvttOutputOptions**)
    public void GetItem(uint i, NvttSurface** pImg, int* face, int* mipmap, NvttOutputOptions** outputOptions)
    {
        Api.nvttBatchListGetItem(
            (NvttBatchList*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            i,
            pImg,
            face,
            mipmap,
            outputOptions);
    }
}
