// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttCubeSurface : System.IDisposable
{
    // From: nvttCreateCubeSurface()
    public static NvttCubeSurface* Create()
    {
        return Api.nvttCreateCubeSurface();
    }

    // From: nvttDestroyCubeSurface(NvttCubeSurface*)
    public void Dispose()
    {
        Api.nvttDestroyCubeSurface((NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttCubeSurfaceIsNull(NvttCubeSurface*)
    public NvttBoolean IsNull()
    {
        return Api.nvttCubeSurfaceIsNull((NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttCubeSurfaceEdgeLength(NvttCubeSurface*)
    public int EdgeLength()
    {
        return Api.nvttCubeSurfaceEdgeLength((NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttCubeSurfaceCountMipmaps(NvttCubeSurface*)
    public int CountMipmaps()
    {
        return Api.nvttCubeSurfaceCountMipmaps((NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttCubeSurfaceLoad(NvttCubeSurface*, sbyte*, int)
    public NvttBoolean Load(ReadOnlySpan<byte> fileName, int mipmap)
    {
        fixed (byte* pfileName = fileName)
        {
            return Api.nvttCubeSurfaceLoad(
                (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName,
                mipmap);
        }
    }

    // From: nvttCubeSurfaceLoadFromMemory(NvttCubeSurface*, void*, ulong, int)
    public NvttBoolean LoadFromMemory(void* data, ulong sizeInBytes, int mipmap)
    {
        return Api.nvttCubeSurfaceLoadFromMemory(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            sizeInBytes,
            mipmap);
    }

    // From: nvttCubeSurfaceSave(NvttCubeSurface*, sbyte*)
    public NvttBoolean Save(ReadOnlySpan<byte> fileName)
    {
        fixed (byte* pfileName = fileName)
        {
            return Api.nvttCubeSurfaceSave(
                (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName);
        }
    }

    // From: nvttCubeSurfaceFace(NvttCubeSurface*, int)
    public NvttSurface* Face(int face)
    {
        return Api.nvttCubeSurfaceFace(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            face);
    }

    // From: nvttCubeSurfaceFold(NvttCubeSurface*, NvttSurface*, NvttCubeLayout)
    public void Fold(NvttSurface* img, NvttCubeLayout layout)
    {
        Api.nvttCubeSurfaceFold(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            layout);
    }

    // From: nvttCubeSurfaceUnfold(NvttCubeSurface*, NvttCubeLayout)
    public NvttSurface* Unfold(NvttCubeLayout layout)
    {
        return Api.nvttCubeSurfaceUnfold(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            layout);
    }

    // From: nvttCubeSurfaceAverage(NvttCubeSurface*, int)
    public float Average(int channel)
    {
        return Api.nvttCubeSurfaceAverage(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel);
    }

    // From: nvttCubeSurfaceRange(NvttCubeSurface*, int, float*, float*)
    public void Range(int channel, float* minimum_ptr, float* maximum_ptr)
    {
        Api.nvttCubeSurfaceRange(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            minimum_ptr,
            maximum_ptr);
    }

    // From: nvttCubeSurfaceClamp(NvttCubeSurface*, int, float, float)
    public void Clamp(int channel, float low, float high)
    {
        Api.nvttCubeSurfaceClamp(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            low,
            high);
    }

    // From: nvttCubeSurfaceIrradianceFilter(NvttCubeSurface*, int, EdgeFixup)
    public NvttCubeSurface* IrradianceFilter(int size, EdgeFixup fixupMethod)
    {
        return Api.nvttCubeSurfaceIrradianceFilter(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            size,
            fixupMethod);
    }

    // From: nvttCubeSurfaceCosinePowerFilter(NvttCubeSurface*, int, float, EdgeFixup)
    public NvttCubeSurface* CosinePowerFilter(int size, float cosinePower, EdgeFixup fixupMethod)
    {
        return Api.nvttCubeSurfaceCosinePowerFilter(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            size,
            cosinePower,
            fixupMethod);
    }

    // From: nvttCubeSurfaceFastResample(NvttCubeSurface*, int, EdgeFixup)
    public NvttCubeSurface* FastResample(int size, EdgeFixup fixupMethod)
    {
        return Api.nvttCubeSurfaceFastResample(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            size,
            fixupMethod);
    }

    // From: nvttCubeSurfaceToLinear(NvttCubeSurface*, float)
    public void ToLinear(float gamma)
    {
        Api.nvttCubeSurfaceToLinear(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            gamma);
    }

    // From: nvttCubeSurfaceToGamma(NvttCubeSurface*, float)
    public void ToGamma(float gamma)
    {
        Api.nvttCubeSurfaceToGamma(
            (NvttCubeSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            gamma);
    }
}
