// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttSurfaceSet : System.IDisposable
{
    // From: nvttCreateSurfaceSet()
    public static NvttSurfaceSet* Create()
    {
        return Api.nvttCreateSurfaceSet();
    }

    // From: nvttDestroySurfaceSet(NvttSurfaceSet*)
    public void Dispose()
    {
        Api.nvttDestroySurfaceSet((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttResetSurfaceSet(NvttSurfaceSet*)
    public void Reset()
    {
        Api.nvttResetSurfaceSet((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetTextureType(NvttSurfaceSet*)
    public NvttTextureType GetTextureType()
    {
        return Api.nvttSurfaceSetGetTextureType((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetFaceCount(NvttSurfaceSet*)
    public int GetFaceCount()
    {
        return Api.nvttSurfaceSetGetFaceCount((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetMipmapCount(NvttSurfaceSet*)
    public int GetMipmapCount()
    {
        return Api.nvttSurfaceSetGetMipmapCount((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetWidth(NvttSurfaceSet*)
    public int GetWidth()
    {
        return Api.nvttSurfaceSetGetWidth((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetHeight(NvttSurfaceSet*)
    public int GetHeight()
    {
        return Api.nvttSurfaceSetGetHeight((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetDepth(NvttSurfaceSet*)
    public int GetDepth()
    {
        return Api.nvttSurfaceSetGetDepth((NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceSetGetSurface(NvttSurfaceSet*, int, int, NvttBoolean)
    public NvttSurface* GetSurface(int faceId, int mipId, NvttBoolean expectSigned)
    {
        return Api.nvttSurfaceSetGetSurface(
            (NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            faceId,
            mipId,
            expectSigned);
    }

    // From: nvttSurfaceSetLoadDDS(NvttSurfaceSet*, sbyte*, NvttBoolean)
    public NvttBoolean LoadDDS(ReadOnlySpan<byte> fileName, NvttBoolean forcenormal)
    {
        fixed (byte* pfileName = fileName)
        {
            return Api.nvttSurfaceSetLoadDDS(
                (NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName,
                forcenormal);
        }
    }

    // From: nvttSurfaceSetLoadDDSFromMemory(NvttSurfaceSet*, void*, ulong, NvttBoolean)
    public NvttBoolean LoadDDSFromMemory(void* data, ulong sizeInBytes, NvttBoolean forcenormal)
    {
        return Api.nvttSurfaceSetLoadDDSFromMemory(
            (NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            sizeInBytes,
            forcenormal);
    }

    // From: nvttSurfaceSetSaveImage(NvttSurfaceSet*, sbyte*, int, int)
    public NvttBoolean SaveImage(ReadOnlySpan<byte> fileName, int faceId, int mipId)
    {
        fixed (byte* pfileName = fileName)
        {
            return Api.nvttSurfaceSetSaveImage(
                (NvttSurfaceSet*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName,
                faceId,
                mipId);
        }
    }
}
