// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttSurface : System.IDisposable
{
    // From: nvttCreateSurface()
    public static NvttSurface* Create()
    {
        return Api.nvttCreateSurface();
    }

    // From: nvttDestroySurface(NvttSurface*)
    public void Dispose()
    {
        Api.nvttDestroySurface((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceClone(NvttSurface*)
    public NvttSurface* Clone()
    {
        return Api.nvttSurfaceClone((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSetSurfaceWrapMode(NvttSurface*, NvttWrapMode)
    public void SetWrapMode(NvttWrapMode mode)
    {
        Api.nvttSetSurfaceWrapMode(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mode);
    }

    // From: nvttSetSurfaceAlphaMode(NvttSurface*, NvttAlphaMode)
    public void SetAlphaMode(NvttAlphaMode alphaMode)
    {
        Api.nvttSetSurfaceAlphaMode(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            alphaMode);
    }

    // From: nvttSetSurfaceNormalMap(NvttSurface*, NvttBoolean)
    public void SetNormalMap(NvttBoolean isNormalMap)
    {
        Api.nvttSetSurfaceNormalMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            isNormalMap);
    }

    // From: nvttSurfaceIsNull(NvttSurface*)
    public NvttBoolean IsNull()
    {
        return Api.nvttSurfaceIsNull((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceWidth(NvttSurface*)
    public int Width()
    {
        return Api.nvttSurfaceWidth((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceHeight(NvttSurface*)
    public int Height()
    {
        return Api.nvttSurfaceHeight((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceDepth(NvttSurface*)
    public int Depth()
    {
        return Api.nvttSurfaceDepth((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceType(NvttSurface*)
    public NvttTextureType Type()
    {
        return Api.nvttSurfaceType((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceWrapMode(NvttSurface*)
    public NvttWrapMode WrapMode()
    {
        return Api.nvttSurfaceWrapMode((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceAlphaMode(NvttSurface*)
    public NvttAlphaMode AlphaMode()
    {
        return Api.nvttSurfaceAlphaMode((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceIsNormalMap(NvttSurface*)
    public NvttBoolean IsNormalMap()
    {
        return Api.nvttSurfaceIsNormalMap((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceCountMipmaps(NvttSurface*, int)
    public int CountMipmaps(int min_size)
    {
        return Api.nvttSurfaceCountMipmaps(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            min_size);
    }

    // From: nvttSurfaceAlphaTestCoverage(NvttSurface*, float, int)
    public float AlphaTestCoverage(float alphaRef, int alpha_channel)
    {
        return Api.nvttSurfaceAlphaTestCoverage(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            alphaRef,
            alpha_channel);
    }

    // From: nvttSurfaceAverage(NvttSurface*, int, int, float)
    public float Average(int channel, int alpha_channel, float gamma)
    {
        return Api.nvttSurfaceAverage(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            alpha_channel,
            gamma);
    }

    // From: nvttSurfaceData(NvttSurface*)
    public float* Data()
    {
        return Api.nvttSurfaceData((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceChannel(NvttSurface*, int)
    public float* Channel(int i)
    {
        return Api.nvttSurfaceChannel(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            i);
    }

    // From: nvttSurfaceHistogram(NvttSurface*, int, float, float, int, int*, NvttTimingContext*)
    public void Histogram(int channel, float rangeMin, float rangeMax, int binCount, int* binPtr, NvttTimingContext* tc)
    {
        Api.nvttSurfaceHistogram(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            rangeMin,
            rangeMax,
            binCount,
            binPtr,
            tc);
    }

    // From: nvttSurfaceRange(NvttSurface*, int, float*, float*, int, float, NvttTimingContext*)
    public void Range(int channel, float* rangeMin, float* rangeMax, int alpha_channel, float alpha_ref, NvttTimingContext* tc)
    {
        Api.nvttSurfaceRange(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            rangeMin,
            rangeMax,
            alpha_channel,
            alpha_ref,
            tc);
    }

    // From: nvttSurfaceLoad(NvttSurface*, sbyte*, NvttBoolean*, NvttBoolean, NvttTimingContext*)
    public NvttBoolean Load(ReadOnlySpan<byte> filename, NvttBoolean* hasAlpha, NvttBoolean expectSigned, NvttTimingContext* tc)
    {
        fixed (byte* pfilename = filename)
        {
            return Api.nvttSurfaceLoad(
                (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfilename,
                hasAlpha,
                expectSigned,
                tc);
        }
    }

    // From: nvttSurfaceLoadFromMemory(NvttSurface*, void*, ulong, NvttBoolean*, NvttBoolean, NvttTimingContext*)
    public NvttBoolean LoadFromMemory(void* data, ulong sizeInBytes, NvttBoolean* hasAlpha, NvttBoolean expectSigned, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceLoadFromMemory(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            data,
            sizeInBytes,
            hasAlpha,
            expectSigned,
            tc);
    }

    // From: nvttSurfaceSave(NvttSurface*, sbyte*, NvttBoolean, NvttBoolean, NvttTimingContext*)
    public NvttBoolean Save(ReadOnlySpan<byte> fileName, NvttBoolean hasAlpha, NvttBoolean hdr, NvttTimingContext* tc)
    {
        fixed (byte* pfileName = fileName)
        {
            return Api.nvttSurfaceSave(
                (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName,
                hasAlpha,
                hdr,
                tc);
        }
    }

    // From: nvttSurfaceSetImage(NvttSurface*, int, int, int, NvttTimingContext*)
    public NvttBoolean SetImage(int w, int h, int d, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceSetImage(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            w,
            h,
            d,
            tc);
    }

    // From: nvttSurfaceSetImageData(NvttSurface*, NvttInputFormat, int, int, int, void*, NvttBoolean, NvttTimingContext*)
    public NvttBoolean SetImageData(NvttInputFormat format, int w, int h, int d, void* data, NvttBoolean unsignedToSigned, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceSetImageData(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            format,
            w,
            h,
            d,
            data,
            unsignedToSigned,
            tc);
    }

    // From: nvttSurfaceSetImageRGBA(NvttSurface*, NvttInputFormat, int, int, int, void*, void*, void*, void*, NvttTimingContext*)
    public NvttBoolean SetImageRGBA(NvttInputFormat format, int w, int h, int d, void* r, void* g, void* b, void* a, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceSetImageRGBA(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            format,
            w,
            h,
            d,
            r,
            g,
            b,
            a,
            tc);
    }

    // From: nvttSurfaceSetImage2D(NvttSurface*, NvttFormat, int, int, void*, NvttTimingContext*)
    public NvttBoolean SetImage2D(NvttFormat format, int w, int h, void* data, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceSetImage2D(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            format,
            w,
            h,
            data,
            tc);
    }

    // From: nvttSurfaceSetImage3D(NvttSurface*, NvttFormat, int, int, int, void*, NvttTimingContext*)
    public NvttBoolean SetImage3D(NvttFormat format, int w, int h, int d, void* data, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceSetImage3D(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            format,
            w,
            h,
            d,
            data,
            tc);
    }

    // From: nvttSurfaceResize(NvttSurface*, int, int, int, NvttResizeFilter, float, float*, NvttTimingContext*)
    public void Resize(int w, int h, int d, NvttResizeFilter filter, float filterWidth, float* @params, NvttTimingContext* tc)
    {
        Api.nvttSurfaceResize(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            w,
            h,
            d,
            filter,
            filterWidth,
            @params,
            tc);
    }

    // From: nvttSurfaceResizeMax(NvttSurface*, int, NvttRoundMode, NvttResizeFilter, NvttTimingContext*)
    public void ResizeMax(int maxExtent, NvttRoundMode mode, NvttResizeFilter filter, NvttTimingContext* tc)
    {
        Api.nvttSurfaceResizeMax(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            maxExtent,
            mode,
            filter,
            tc);
    }

    // From: nvttSurfaceResizeMaxParams(NvttSurface*, int, NvttRoundMode, NvttResizeFilter, float, float*, NvttTimingContext*)
    public void ResizeMaxParams(int maxExtent, NvttRoundMode mode, NvttResizeFilter filter, float filterWidth, float* @params, NvttTimingContext* tc)
    {
        Api.nvttSurfaceResizeMaxParams(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            maxExtent,
            mode,
            filter,
            filterWidth,
            @params,
            tc);
    }

    // From: nvttSurfaceResizeMakeSquare(NvttSurface*, int, NvttRoundMode, NvttResizeFilter, NvttTimingContext*)
    public void ResizeMakeSquare(int maxExtent, NvttRoundMode mode, NvttResizeFilter filter, NvttTimingContext* tc)
    {
        Api.nvttSurfaceResizeMakeSquare(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            maxExtent,
            mode,
            filter,
            tc);
    }

    // From: nvttSurfaceBuildNextMipmap(NvttSurface*, NvttMipmapFilter, float, float*, int, NvttTimingContext*)
    public NvttBoolean BuildNextMipmap(NvttMipmapFilter filter, float filterWidth, float* @params, int min_size, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceBuildNextMipmap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            filter,
            filterWidth,
            @params,
            min_size,
            tc);
    }

    // From: nvttSurfaceBuildNextMipmapDefaults(NvttSurface*, NvttMipmapFilter, int, NvttTimingContext*)
    public NvttBoolean BuildNextMipmapDefaults(NvttMipmapFilter filter, int min_size, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceBuildNextMipmapDefaults(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            filter,
            min_size,
            tc);
    }

    // From: nvttSurfaceBuildNextMipmapSolidColor(NvttSurface*, float*, NvttTimingContext*)
    public NvttBoolean BuildNextMipmapSolidColor(float* color_components, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceBuildNextMipmapSolidColor(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            color_components,
            tc);
    }

    // From: nvttSurfaceCanvasSize(NvttSurface*, int, int, int, NvttTimingContext*)
    public void CanvasSize(int w, int h, int d, NvttTimingContext* tc)
    {
        Api.nvttSurfaceCanvasSize(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            w,
            h,
            d,
            tc);
    }

    // From: nvttSurfaceCanMakeNextMipmap(NvttSurface*, int)
    public NvttBoolean CanMakeNextMipmap(int min_size)
    {
        return Api.nvttSurfaceCanMakeNextMipmap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            min_size);
    }

    // From: nvttSurfaceToLinear(NvttSurface*, float, NvttTimingContext*)
    public void ToLinear(float gamma, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLinear(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            gamma,
            tc);
    }

    // From: nvttSurfaceToGamma(NvttSurface*, float, NvttTimingContext*)
    public void ToGamma(float gamma, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToGamma(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            gamma,
            tc);
    }

    // From: nvttSurfaceToLinearChannel(NvttSurface*, int, float, NvttTimingContext*)
    public void ToLinearChannel(int channel, float gamma, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLinearChannel(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            gamma,
            tc);
    }

    // From: nvttSurfaceToGammaChannel(NvttSurface*, int, float, NvttTimingContext*)
    public void ToGammaChannel(int channel, float gamma, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToGammaChannel(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            gamma,
            tc);
    }

    // From: nvttSurfaceToSrgb(NvttSurface*, NvttTimingContext*)
    public void ToSrgb(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToSrgb(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToSrgbUnclamped(NvttSurface*, NvttTimingContext*)
    public void ToSrgbUnclamped(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToSrgbUnclamped(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToLinearFromSrgb(NvttSurface*, NvttTimingContext*)
    public void ToLinearFromSrgb(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLinearFromSrgb(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToLinearFromSrgbUnclamped(NvttSurface*, NvttTimingContext*)
    public void ToLinearFromSrgbUnclamped(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLinearFromSrgbUnclamped(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToXenonSrgb(NvttSurface*, NvttTimingContext*)
    public void ToXenonSrgb(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToXenonSrgb(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToLinearFromXenonSrgb(NvttSurface*, NvttTimingContext*)
    public void ToLinearFromXenonSrgb(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLinearFromXenonSrgb(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceTransform(NvttSurface*, float*, float*, float*, float*, float*, NvttTimingContext*)
    public void Transform(float* w0, float* w1, float* w2, float* w3, float* offset, NvttTimingContext* tc)
    {
        Api.nvttSurfaceTransform(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            w0,
            w1,
            w2,
            w3,
            offset,
            tc);
    }

    // From: nvttSurfaceSwizzle(NvttSurface*, int, int, int, int, NvttTimingContext*)
    public void Swizzle(int r, int g, int b, int a, NvttTimingContext* tc)
    {
        Api.nvttSurfaceSwizzle(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            r,
            g,
            b,
            a,
            tc);
    }

    // From: nvttSurfaceScaleBias(NvttSurface*, int, float, float, NvttTimingContext*)
    public void ScaleBias(int channel, float scale, float bias, NvttTimingContext* tc)
    {
        Api.nvttSurfaceScaleBias(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            scale,
            bias,
            tc);
    }

    // From: nvttSurfaceClamp(NvttSurface*, int, float, float, NvttTimingContext*)
    public void Clamp(int channel, float low, float high, NvttTimingContext* tc)
    {
        Api.nvttSurfaceClamp(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            low,
            high,
            tc);
    }

    // From: nvttSurfaceBlend(NvttSurface*, float, float, float, float, float, NvttTimingContext*)
    public void Blend(float r, float g, float b, float a, float t, NvttTimingContext* tc)
    {
        Api.nvttSurfaceBlend(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            r,
            g,
            b,
            a,
            t,
            tc);
    }

    // From: nvttSurfacePremultiplyAlpha(NvttSurface*, NvttTimingContext*)
    public void PremultiplyAlpha(NvttTimingContext* tc)
    {
        Api.nvttSurfacePremultiplyAlpha(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceDemultiplyAlpha(NvttSurface*, float, NvttTimingContext*)
    public void DemultiplyAlpha(float epsilon, NvttTimingContext* tc)
    {
        Api.nvttSurfaceDemultiplyAlpha(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            epsilon,
            tc);
    }

    // From: nvttSurfaceToGreyScale(NvttSurface*, float, float, float, float, NvttTimingContext*)
    public void ToGreyScale(float redScale, float greenScale, float blueScale, float alphaScale, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToGreyScale(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            redScale,
            greenScale,
            blueScale,
            alphaScale,
            tc);
    }

    // From: nvttSurfaceSetBorder(NvttSurface*, float, float, float, float, NvttTimingContext*)
    public void SetBorder(float r, float g, float b, float a, NvttTimingContext* tc)
    {
        Api.nvttSurfaceSetBorder(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            r,
            g,
            b,
            a,
            tc);
    }

    // From: nvttSurfaceFill(NvttSurface*, float, float, float, float, NvttTimingContext*)
    public void Fill(float r, float g, float b, float a, NvttTimingContext* tc)
    {
        Api.nvttSurfaceFill(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            r,
            g,
            b,
            a,
            tc);
    }

    // From: nvttSurfaceScaleAlphaToCoverage(NvttSurface*, float, float, int, NvttTimingContext*)
    public void ScaleAlphaToCoverage(float coverage, float alphaRef, int alpha_channel, NvttTimingContext* tc)
    {
        Api.nvttSurfaceScaleAlphaToCoverage(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            coverage,
            alphaRef,
            alpha_channel,
            tc);
    }

    // From: nvttSurfaceToRGBM(NvttSurface*, float, float, NvttTimingContext*)
    public void ToRGBM(float range, float threshold, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToRGBM(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            range,
            threshold,
            tc);
    }

    // From: nvttSurfaceFromRGBM(NvttSurface*, float, float, NvttTimingContext*)
    public void FromRGBM(float range, float threshold, NvttTimingContext* tc)
    {
        Api.nvttSurfaceFromRGBM(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            range,
            threshold,
            tc);
    }

    // From: nvttSurfaceToLM(NvttSurface*, float, float, NvttTimingContext*)
    public void ToLM(float range, float threshold, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLM(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            range,
            threshold,
            tc);
    }

    // From: nvttSurfaceToRGBE(NvttSurface*, int, int, NvttTimingContext*)
    public void ToRGBE(int mantissaBits, int exponentBits, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToRGBE(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mantissaBits,
            exponentBits,
            tc);
    }

    // From: nvttSurfaceFromRGBE(NvttSurface*, int, int, NvttTimingContext*)
    public void FromRGBE(int mantissaBits, int exponentBits, NvttTimingContext* tc)
    {
        Api.nvttSurfaceFromRGBE(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            mantissaBits,
            exponentBits,
            tc);
    }

    // From: nvttSurfaceToYCoCg(NvttSurface*, NvttTimingContext*)
    public void ToYCoCg(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToYCoCg(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceBlockScaleCoCg(NvttSurface*, int, float, NvttTimingContext*)
    public void BlockScaleCoCg(int bits, float threshold, NvttTimingContext* tc)
    {
        Api.nvttSurfaceBlockScaleCoCg(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            bits,
            threshold,
            tc);
    }

    // From: nvttSurfaceFromYCoCg(NvttSurface*, NvttTimingContext*)
    public void FromYCoCg(NvttTimingContext* tc)
    {
        Api.nvttSurfaceFromYCoCg(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceToLUVW(NvttSurface*, float, NvttTimingContext*)
    public void ToLUVW(float range, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLUVW(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            range,
            tc);
    }

    // From: nvttSurfaceFromLUVW(NvttSurface*, float, NvttTimingContext*)
    public void FromLUVW(float range, NvttTimingContext* tc)
    {
        Api.nvttSurfaceFromLUVW(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            range,
            tc);
    }

    // From: nvttSurfaceAbs(NvttSurface*, int, NvttTimingContext*)
    public void Abs(int channel, NvttTimingContext* tc)
    {
        Api.nvttSurfaceAbs(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            tc);
    }

    // From: nvttSurfaceConvolve(NvttSurface*, int, int, float*, NvttTimingContext*)
    public void Convolve(int channel, int kernelSize, float* kernelData, NvttTimingContext* tc)
    {
        Api.nvttSurfaceConvolve(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            kernelSize,
            kernelData,
            tc);
    }

    // From: nvttSurfaceToLogScale(NvttSurface*, int, float, NvttTimingContext*)
    public void ToLogScale(int channel, float @base, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToLogScale(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            @base,
            tc);
    }

    // From: nvttSurfaceFromLogScale(NvttSurface*, int, float, NvttTimingContext*)
    public void FromLogScale(int channel, float @base, NvttTimingContext* tc)
    {
        Api.nvttSurfaceFromLogScale(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            @base,
            tc);
    }

    // From: nvttSurfaceSetAtlasBorder(NvttSurface*, int, int, float, float, float, float, NvttTimingContext*)
    public void SetAtlasBorder(int w, int h, float r, float g, float b, float a, NvttTimingContext* tc)
    {
        Api.nvttSurfaceSetAtlasBorder(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            w,
            h,
            r,
            g,
            b,
            a,
            tc);
    }

    // From: nvttSurfaceToneMap(NvttSurface*, NvttToneMapper, float*, NvttTimingContext*)
    public void ToneMap(NvttToneMapper tm, float* parameters, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToneMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tm,
            parameters,
            tc);
    }

    // From: nvttSurfaceBinarize(NvttSurface*, int, float, NvttBoolean, NvttTimingContext*)
    public void Binarize(int channel, float threshold, NvttBoolean dither, NvttTimingContext* tc)
    {
        Api.nvttSurfaceBinarize(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            threshold,
            dither,
            tc);
    }

    // From: nvttSurfaceQuantize(NvttSurface*, int, int, NvttBoolean, NvttBoolean, NvttTimingContext*)
    public void Quantize(int channel, int bits, NvttBoolean exactEndPoints, NvttBoolean dither, NvttTimingContext* tc)
    {
        Api.nvttSurfaceQuantize(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            channel,
            bits,
            exactEndPoints,
            dither,
            tc);
    }

    // From: nvttSurfaceToNormalMap(NvttSurface*, float, float, float, float, NvttTimingContext*)
    public void ToNormalMap(float sm, float medium, float big, float large, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToNormalMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            sm,
            medium,
            big,
            large,
            tc);
    }

    // From: nvttSurfaceNormalizeNormalMap(NvttSurface*, NvttTimingContext*)
    public void NormalizeNormalMap(NvttTimingContext* tc)
    {
        Api.nvttSurfaceNormalizeNormalMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceTransformNormals(NvttSurface*, NvttNormalTransform, NvttTimingContext*)
    public void TransformNormals(NvttNormalTransform xform, NvttTimingContext* tc)
    {
        Api.nvttSurfaceTransformNormals(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            xform,
            tc);
    }

    // From: nvttSurfaceReconstructNormals(NvttSurface*, NvttNormalTransform, NvttTimingContext*)
    public void ReconstructNormals(NvttNormalTransform xform, NvttTimingContext* tc)
    {
        Api.nvttSurfaceReconstructNormals(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            xform,
            tc);
    }

    // From: nvttSurfaceToCleanNormalMap(NvttSurface*, NvttTimingContext*)
    public void ToCleanNormalMap(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToCleanNormalMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfacePackNormals(NvttSurface*, float, float, NvttTimingContext*)
    public void PackNormals(float scale, float bias, NvttTimingContext* tc)
    {
        Api.nvttSurfacePackNormals(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            scale,
            bias,
            tc);
    }

    // From: nvttSurfaceExpandNormals(NvttSurface*, float, float, NvttTimingContext*)
    public void ExpandNormals(float scale, float bias, NvttTimingContext* tc)
    {
        Api.nvttSurfaceExpandNormals(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            scale,
            bias,
            tc);
    }

    // From: nvttSurfaceCreateToksvigMap(NvttSurface*, float, NvttTimingContext*)
    public NvttSurface* CreateToksvigMap(float power, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceCreateToksvigMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            power,
            tc);
    }

    // From: nvttSurfaceCreateCleanMap(NvttSurface*, NvttTimingContext*)
    public NvttSurface* CreateCleanMap(NvttTimingContext* tc)
    {
        return Api.nvttSurfaceCreateCleanMap(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceFlipX(NvttSurface*, NvttTimingContext*)
    public void FlipX(NvttTimingContext* tc)
    {
        Api.nvttSurfaceFlipX(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceFlipY(NvttSurface*, NvttTimingContext*)
    public void FlipY(NvttTimingContext* tc)
    {
        Api.nvttSurfaceFlipY(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceFlipZ(NvttSurface*, NvttTimingContext*)
    public void FlipZ(NvttTimingContext* tc)
    {
        Api.nvttSurfaceFlipZ(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceCreateSubImage(NvttSurface*, int, int, int, int, int, int, NvttTimingContext*)
    public NvttSurface* CreateSubImage(int x0, int x1, int y0, int y1, int z0, int z1, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceCreateSubImage(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            x0,
            x1,
            y0,
            y1,
            z0,
            z1,
            tc);
    }

    // From: nvttSurfaceCopyChannel(NvttSurface*, NvttSurface*, int, int, NvttTimingContext*)
    public NvttBoolean CopyChannel(NvttSurface* srcImage, int srcChannel, int dstChannel, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceCopyChannel(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            srcImage,
            srcChannel,
            dstChannel,
            tc);
    }

    // From: nvttSurfaceAddChannel(NvttSurface*, NvttSurface*, int, int, float, NvttTimingContext*)
    public NvttBoolean AddChannel(NvttSurface* srcImage, int srcChannel, int dstChannel, float scale, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceAddChannel(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            srcImage,
            srcChannel,
            dstChannel,
            scale,
            tc);
    }

    // From: nvttSurfaceCopy(NvttSurface*, NvttSurface*, int, int, int, int, int, int, int, int, int, NvttTimingContext*)
    public NvttBoolean Copy(NvttSurface* srcImage, int xsrc, int ysrc, int zsrc, int xsize, int ysize, int zsize, int xdst, int ydst, int zdst, NvttTimingContext* tc)
    {
        return Api.nvttSurfaceCopy(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            srcImage,
            xsrc,
            ysrc,
            zsrc,
            xsize,
            ysize,
            zsize,
            xdst,
            ydst,
            zdst,
            tc);
    }

    // From: nvttSurfaceToGPU(NvttSurface*, NvttBoolean, NvttTimingContext*)
    public void ToGPU(NvttBoolean performCopy, NvttTimingContext* tc)
    {
        Api.nvttSurfaceToGPU(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            performCopy,
            tc);
    }

    // From: nvttSurfaceToCPU(NvttSurface*, NvttTimingContext*)
    public void ToCPU(NvttTimingContext* tc)
    {
        Api.nvttSurfaceToCPU(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tc);
    }

    // From: nvttSurfaceGPUData(NvttSurface*)
    public float* GPUData()
    {
        return Api.nvttSurfaceGPUData((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSurfaceGPUDataMutable(NvttSurface*)
    public float* GPUDataMutable()
    {
        return Api.nvttSurfaceGPUDataMutable((NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttRmsError(NvttSurface*, NvttSurface*, NvttTimingContext*)
    public float RmsError(NvttSurface* img, NvttTimingContext* tc)
    {
        return Api.nvttRmsError(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            tc);
    }

    // From: nvttRmsAlphaError(NvttSurface*, NvttSurface*, NvttTimingContext*)
    public float RmsAlphaError(NvttSurface* img, NvttTimingContext* tc)
    {
        return Api.nvttRmsAlphaError(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            tc);
    }

    // From: nvttRmsCIELabError(NvttSurface*, NvttSurface*, NvttTimingContext*)
    public float RmsCIELabError(NvttSurface* img, NvttTimingContext* tc)
    {
        return Api.nvttRmsCIELabError(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            tc);
    }

    // From: nvttAngularError(NvttSurface*, NvttSurface*, NvttTimingContext*)
    public float AngularError(NvttSurface* img, NvttTimingContext* tc)
    {
        return Api.nvttAngularError(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            tc);
    }

    // From: nvttDiff(NvttSurface*, NvttSurface*, float, NvttTimingContext*)
    public NvttSurface* Diff(NvttSurface* img, float scale, NvttTimingContext* tc)
    {
        return Api.nvttDiff(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            scale,
            tc);
    }

    // From: nvttRmsToneMappedError(NvttSurface*, NvttSurface*, float, NvttTimingContext*)
    public float RmsToneMappedError(NvttSurface* img, float exposure, NvttTimingContext* tc)
    {
        return Api.nvttRmsToneMappedError(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            img,
            exposure,
            tc);
    }

    // From: nvttHistogram(NvttSurface*, int, int, NvttTimingContext*)
    public NvttSurface* Histogram(int width, int height, NvttTimingContext* tc)
    {
        return Api.nvttHistogram(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            width,
            height,
            tc);
    }

    // From: nvttHistogramRange(NvttSurface*, float, float, int, int, NvttTimingContext*)
    public NvttSurface* HistogramRange(float minRange, float maxRange, int width, int height, NvttTimingContext* tc)
    {
        return Api.nvttHistogramRange(
            (NvttSurface*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            minRange,
            maxRange,
            width,
            height,
            tc);
    }
}
