// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttGPUInputBuffer : System.IDisposable
{
    // From: nvttDestroyGPUInputBuffer(NvttGPUInputBuffer*)
    public void Dispose()
    {
        Api.nvttDestroyGPUInputBuffer((NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttGPUInputBufferNumTiles(NvttGPUInputBuffer*)
    public int NumTiles()
    {
        return Api.nvttGPUInputBufferNumTiles((NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttGPUInputBufferTileSize(NvttGPUInputBuffer*, int*, int*)
    public void TileSize(int* tile_w, int* tile_h)
    {
        Api.nvttGPUInputBufferTileSize(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            tile_w,
            tile_h);
    }

    // From: nvttGPUInputBufferType(NvttGPUInputBuffer*)
    public NvttValueType Type()
    {
        return Api.nvttGPUInputBufferType((NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttEncodeGPU(NvttGPUInputBuffer*, void*, NvttEncodeSettings*)
    public NvttBoolean EncodeGPU(void* output, NvttEncodeSettings* settings)
    {
        return Api.nvttEncodeGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            settings);
    }

    // From: nvttEncodeBC1GPU(NvttGPUInputBuffer*, NvttBoolean, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC1GPU(NvttBoolean fast_mode, void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC1GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            fast_mode,
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC1AGPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC1AGPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC1AGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC2GPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC2GPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC2GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC3GPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC3GPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC3GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC4GPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC4GPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC4GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC4SGPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC4SGPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC4SGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeATI2GPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeATI2GPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeATI2GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC5GPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC5GPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC5GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC5SGPU(NvttGPUInputBuffer*, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC5SGPU(void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC5SGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC6HGPU(NvttGPUInputBuffer*, NvttBoolean, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC6HGPU(NvttBoolean is_signed, void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC6HGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            is_signed,
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeBC7GPU(NvttGPUInputBuffer*, NvttBoolean, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeBC7GPU(NvttBoolean imageHasAlpha, void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeBC7GPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            imageHasAlpha,
            output,
            to_device_mem,
            tc);
    }

    // From: nvttEncodeASTCGPU(NvttGPUInputBuffer*, int, NvttBoolean, void*, NvttBoolean, NvttTimingContext*)
    public void EncodeASTCGPU(int qualityLevel, NvttBoolean imageHasAlpha, void* output, NvttBoolean to_device_mem, NvttTimingContext* tc)
    {
        Api.nvttEncodeASTCGPU(
            (NvttGPUInputBuffer*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            qualityLevel,
            imageHasAlpha,
            output,
            to_device_mem,
            tc);
    }
}
