// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.Nvtt;

public unsafe partial struct NvttOutputOptions : System.IDisposable
{
    // From: nvttCreateOutputOptions()
    public static NvttOutputOptions* Create()
    {
        return Api.nvttCreateOutputOptions();
    }

    // From: nvttDestroyOutputOptions(NvttOutputOptions*)
    public void Dispose()
    {
        Api.nvttDestroyOutputOptions((NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttResetOutputOptions(NvttOutputOptions*)
    public void Reset()
    {
        Api.nvttResetOutputOptions((NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this));
    }

    // From: nvttSetOutputOptionsFileName(NvttOutputOptions*, sbyte*)
    public void SetFileName(ReadOnlySpan<byte> fileName)
    {
        fixed (byte* pfileName = fileName)
        {
            Api.nvttSetOutputOptionsFileName(
                (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
                (sbyte*)pfileName);
        }
    }

    // From: nvttSetOutputOptionsFileHandle(NvttOutputOptions*, void*)
    public void SetFileHandle(void* fp)
    {
        Api.nvttSetOutputOptionsFileHandle(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            fp);
    }

    // From: nvttSetOutputOptionsOutputHandler(NvttOutputOptions*, delegate* unmanaged[Cdecl]<int, int, int, int, int, int, void>, delegate* unmanaged[Cdecl]<void*, int, NvttBoolean>, IntPtr)
    public void SetOutputHandler(delegate* unmanaged[Cdecl]<int, int, int, int, int, int, void> beginImageHandler, delegate* unmanaged[Cdecl]<void*, int, NvttBoolean> outputHandler, IntPtr endImageHandler)
    {
        Api.nvttSetOutputOptionsOutputHandler(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            beginImageHandler,
            outputHandler,
            endImageHandler);
    }

    // From: nvttSetOutputOptionsErrorHandler(NvttOutputOptions*, delegate* unmanaged[Cdecl]<NvttError, void>)
    public void SetErrorHandler(delegate* unmanaged[Cdecl]<NvttError, void> errorHandler)
    {
        Api.nvttSetOutputOptionsErrorHandler(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            errorHandler);
    }

    // From: nvttSetOutputOptionsOutputHeader(NvttOutputOptions*, NvttBoolean)
    public void SetOutputHeader(NvttBoolean b)
    {
        Api.nvttSetOutputOptionsOutputHeader(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            b);
    }

    // From: nvttSetOutputOptionsContainer(NvttOutputOptions*, NvttContainer)
    public void SetContainer(NvttContainer container)
    {
        Api.nvttSetOutputOptionsContainer(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            container);
    }

    // From: nvttSetOutputOptionsUserVersion(NvttOutputOptions*, int)
    public void SetUserVersion(int version)
    {
        Api.nvttSetOutputOptionsUserVersion(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            version);
    }

    // From: nvttSetOutputOptionsSrgbFlag(NvttOutputOptions*, NvttBoolean)
    public void SetSrgbFlag(NvttBoolean b)
    {
        Api.nvttSetOutputOptionsSrgbFlag(
            (NvttOutputOptions*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref this),
            b);
    }
}
