<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Debug_Editor;Release_Editor</Configurations>
    <DefineConstants>$(DefineConstants);MHP_ENABLE_MIMALLOC;MHP_FASTMATH</DefineConstants>
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug_Editor'">
    <DefineConstants>$(DefineConstants);MHP_ENABLE_SAFETY_CHECKS;MHP_ENABLE_STACKTRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release_Editor'">
    <DefineConstants>$(DefineConstants);MHP_ENABLE_SAFETY_CHECKS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Misaki.HighPerformance" Version="1.0.10" />
    <PackageReference Include="Misaki.HighPerformance.Jobs" Version="3.1.7" />
    <PackageReference Include="Misaki.HighPerformance.LowLevel" Version="1.7.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Misaki.HighPerformance.Mathematics" Version="1.3.4" />
    <PackageReference Include="Misaki.HighPerformance.Mathematics.SPMD" Version="1.3.8" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
    <PackageReference Include="TerraFX.Interop.Mimalloc" Version="1.6.7.2" />
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.26100.6" />
  </ItemGroup>

</Project>
