// <auto-generated>
// This file is generated by Ghost.NativeWrapperGen. Do not edit manually.
// </auto-generated>

namespace Ghost.StbI;

public unsafe partial struct StbIApi
{
    /// <summary>
    /// From: <see cref="Api.stbi_load_from_memory(byte*, int, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static byte* LoadFromMemory(ReadOnlySpan<byte> buffer, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_load_from_memory(
                (byte*)pbuffer,
                buffer.Length,
                x,
                y,
                channels_in_file,
                desired_channels);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load_from_callbacks(stbi_io_callbacks*, void*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static byte* LoadFromCallbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_load_from_callbacks(
            clbk,
            user,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load(sbyte*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static byte* Load(sbyte* filename, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_load(
            filename,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load_gif_from_memory(byte*, int, int**, int*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static byte* LoadGifFromMemory(ReadOnlySpan<byte> buffer, int** delays, int* x, int* y, int* z, int* comp, int req_comp)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_load_gif_from_memory(
                (byte*)pbuffer,
                buffer.Length,
                delays,
                x,
                y,
                z,
                comp,
                req_comp);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load_16_from_memory(byte*, int, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort* Load16FromMemory(ReadOnlySpan<byte> buffer, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_load_16_from_memory(
                (byte*)pbuffer,
                buffer.Length,
                x,
                y,
                channels_in_file,
                desired_channels);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load_16_from_callbacks(stbi_io_callbacks*, void*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort* Load16FromCallbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_load_16_from_callbacks(
            clbk,
            user,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_load_16(sbyte*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort* Load16(sbyte* filename, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_load_16(
            filename,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_loadf_from_memory(byte*, int, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float* LoadfFromMemory(ReadOnlySpan<byte> buffer, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_loadf_from_memory(
                (byte*)pbuffer,
                buffer.Length,
                x,
                y,
                channels_in_file,
                desired_channels);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_loadf_from_callbacks(stbi_io_callbacks*, void*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float* LoadfFromCallbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_loadf_from_callbacks(
            clbk,
            user,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_loadf(sbyte*, int*, int*, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static float* Loadf(sbyte* filename, int* x, int* y, int* channels_in_file, int desired_channels)
    {
        return Api.stbi_loadf(
            filename,
            x,
            y,
            channels_in_file,
            desired_channels);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_hdr_to_ldr_gamma(float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void HdrToLdrGamma(float gamma)
    {
        Api.stbi_hdr_to_ldr_gamma(gamma);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_hdr_to_ldr_scale(float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void HdrToLdrScale(float scale)
    {
        Api.stbi_hdr_to_ldr_scale(scale);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_ldr_to_hdr_gamma(float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void LdrToHdrGamma(float gamma)
    {
        Api.stbi_ldr_to_hdr_gamma(gamma);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_ldr_to_hdr_scale(float)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void LdrToHdrScale(float scale)
    {
        Api.stbi_ldr_to_hdr_scale(scale);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_hdr_from_callbacks(stbi_io_callbacks*, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IsHdrFromCallbacks(stbi_io_callbacks* clbk, void* user)
    {
        return Api.stbi_is_hdr_from_callbacks(
            clbk,
            user);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_hdr_from_memory(byte*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IsHdrFromMemory(ReadOnlySpan<byte> buffer)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_is_hdr_from_memory(
                (byte*)pbuffer,
                buffer.Length);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_hdr(sbyte*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int IsHdr(sbyte* filename)
    {
        return Api.stbi_is_hdr(filename);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_failure_reason()" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static sbyte* FailureReason()
    {
        return Api.stbi_failure_reason();
    }

    /// <summary>
    /// From: <see cref="Api.stbi_image_free(void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void ImageFree(void* retval_from_stbi_load)
    {
        Api.stbi_image_free(retval_from_stbi_load);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_info_from_memory(byte*, int, int*, int*, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int InfoFromMemory(ReadOnlySpan<byte> buffer, int* x, int* y, int* comp)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_info_from_memory(
                (byte*)pbuffer,
                buffer.Length,
                x,
                y,
                comp);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_info_from_callbacks(stbi_io_callbacks*, void*, int*, int*, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int InfoFromCallbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* comp)
    {
        return Api.stbi_info_from_callbacks(
            clbk,
            user,
            x,
            y,
            comp);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_16_bit_from_memory(byte*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Is16BitFromMemory(ReadOnlySpan<byte> buffer)
    {
        fixed (byte* pbuffer = buffer)
        {
            return Api.stbi_is_16_bit_from_memory(
                (byte*)pbuffer,
                buffer.Length);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_16_bit_from_callbacks(stbi_io_callbacks*, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Is16BitFromCallbacks(stbi_io_callbacks* clbk, void* user)
    {
        return Api.stbi_is_16_bit_from_callbacks(
            clbk,
            user);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_info(sbyte*, int*, int*, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Info(sbyte* filename, int* x, int* y, int* comp)
    {
        return Api.stbi_info(
            filename,
            x,
            y,
            comp);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_is_16_bit(sbyte*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Is16Bit(sbyte* filename)
    {
        return Api.stbi_is_16_bit(filename);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_set_unpremultiply_on_load(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void SetUnpremultiplyOnLoad(int flag_true_if_should_unpremultiply)
    {
        Api.stbi_set_unpremultiply_on_load(flag_true_if_should_unpremultiply);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_convert_iphone_png_to_rgb(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void ConvertIphonePngToRgb(int flag_true_if_should_convert)
    {
        Api.stbi_convert_iphone_png_to_rgb(flag_true_if_should_convert);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_set_flip_vertically_on_load(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void SetFlipVerticallyOnLoad(int flag_true_if_should_flip)
    {
        Api.stbi_set_flip_vertically_on_load(flag_true_if_should_flip);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_set_unpremultiply_on_load_thread(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void SetUnpremultiplyOnLoadThread(int flag_true_if_should_unpremultiply)
    {
        Api.stbi_set_unpremultiply_on_load_thread(flag_true_if_should_unpremultiply);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_convert_iphone_png_to_rgb_thread(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void ConvertIphonePngToRgbThread(int flag_true_if_should_convert)
    {
        Api.stbi_convert_iphone_png_to_rgb_thread(flag_true_if_should_convert);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_set_flip_vertically_on_load_thread(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void SetFlipVerticallyOnLoadThread(int flag_true_if_should_flip)
    {
        Api.stbi_set_flip_vertically_on_load_thread(flag_true_if_should_flip);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_malloc_guesssize(sbyte*, int, int, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static sbyte* ZlibDecodeMallocGuesssize(ReadOnlySpan<sbyte> buffer, int initial_size, int* outlen)
    {
        fixed (sbyte* pbuffer = buffer)
        {
            return Api.stbi_zlib_decode_malloc_guesssize(
                (sbyte*)pbuffer,
                buffer.Length,
                initial_size,
                outlen);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_malloc_guesssize_headerflag(sbyte*, int, int, int*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static sbyte* ZlibDecodeMallocGuesssizeHeaderflag(ReadOnlySpan<sbyte> buffer, int initial_size, int* outlen, int parse_header)
    {
        fixed (sbyte* pbuffer = buffer)
        {
            return Api.stbi_zlib_decode_malloc_guesssize_headerflag(
                (sbyte*)pbuffer,
                buffer.Length,
                initial_size,
                outlen,
                parse_header);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_malloc(sbyte*, int, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static sbyte* ZlibDecodeMalloc(ReadOnlySpan<sbyte> buffer, int* outlen)
    {
        fixed (sbyte* pbuffer = buffer)
        {
            return Api.stbi_zlib_decode_malloc(
                (sbyte*)pbuffer,
                buffer.Length,
                outlen);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_buffer(sbyte*, int, sbyte*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int ZlibDecodeBuffer(ReadOnlySpan<sbyte> obuffer, ReadOnlySpan<sbyte> ibuffer)
    {
        fixed (sbyte* pobuffer = obuffer)
        {
            fixed (sbyte* pibuffer = ibuffer)
            {
                return Api.stbi_zlib_decode_buffer(
                    (sbyte*)pobuffer,
                    obuffer.Length,
                    (sbyte*)pibuffer,
                    ibuffer.Length);
            }
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_noheader_malloc(sbyte*, int, int*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static sbyte* ZlibDecodeNoheaderMalloc(ReadOnlySpan<sbyte> buffer, int* outlen)
    {
        fixed (sbyte* pbuffer = buffer)
        {
            return Api.stbi_zlib_decode_noheader_malloc(
                (sbyte*)pbuffer,
                buffer.Length,
                outlen);
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_zlib_decode_noheader_buffer(sbyte*, int, sbyte*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int ZlibDecodeNoheaderBuffer(ReadOnlySpan<sbyte> obuffer, ReadOnlySpan<sbyte> ibuffer)
    {
        fixed (sbyte* pobuffer = obuffer)
        {
            fixed (sbyte* pibuffer = ibuffer)
            {
                return Api.stbi_zlib_decode_noheader_buffer(
                    (sbyte*)pobuffer,
                    obuffer.Length,
                    (sbyte*)pibuffer,
                    ibuffer.Length);
            }
        }
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_png(sbyte*, int, int, int, void*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WritePng(sbyte* filename, int w, int h, int comp, void* data, int stride_in_bytes)
    {
        return Api.stbi_write_png(
            filename,
            w,
            h,
            comp,
            data,
            stride_in_bytes);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_bmp(sbyte*, int, int, int, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteBmp(sbyte* filename, int w, int h, int comp, void* data)
    {
        return Api.stbi_write_bmp(
            filename,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_tga(sbyte*, int, int, int, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteTga(sbyte* filename, int w, int h, int comp, void* data)
    {
        return Api.stbi_write_tga(
            filename,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_hdr(sbyte*, int, int, int, float*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteHdr(sbyte* filename, int w, int h, int comp, float* data)
    {
        return Api.stbi_write_hdr(
            filename,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_jpg(sbyte*, int, int, int, void*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteJpg(sbyte* filename, int x, int y, int comp, void* data, int quality)
    {
        return Api.stbi_write_jpg(
            filename,
            x,
            y,
            comp,
            data,
            quality);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_png_to_func(delegate* unmanaged[Cdecl]<void*, void*, int, void>, void*, int, int, int, void*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WritePngToFunc(delegate* unmanaged[Cdecl]<void*, void*, int, void> func, void* context, int w, int h, int comp, void* data, int stride_in_bytes)
    {
        return Api.stbi_write_png_to_func(
            func,
            context,
            w,
            h,
            comp,
            data,
            stride_in_bytes);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_bmp_to_func(delegate* unmanaged[Cdecl]<void*, void*, int, void>, void*, int, int, int, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteBmpToFunc(delegate* unmanaged[Cdecl]<void*, void*, int, void> func, void* context, int w, int h, int comp, void* data)
    {
        return Api.stbi_write_bmp_to_func(
            func,
            context,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_tga_to_func(delegate* unmanaged[Cdecl]<void*, void*, int, void>, void*, int, int, int, void*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteTgaToFunc(delegate* unmanaged[Cdecl]<void*, void*, int, void> func, void* context, int w, int h, int comp, void* data)
    {
        return Api.stbi_write_tga_to_func(
            func,
            context,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_hdr_to_func(delegate* unmanaged[Cdecl]<void*, void*, int, void>, void*, int, int, int, float*)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteHdrToFunc(delegate* unmanaged[Cdecl]<void*, void*, int, void> func, void* context, int w, int h, int comp, float* data)
    {
        return Api.stbi_write_hdr_to_func(
            func,
            context,
            w,
            h,
            comp,
            data);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_write_jpg_to_func(delegate* unmanaged[Cdecl]<void*, void*, int, void>, void*, int, int, int, void*, int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int WriteJpgToFunc(delegate* unmanaged[Cdecl]<void*, void*, int, void> func, void* context, int x, int y, int comp, void* data, int quality)
    {
        return Api.stbi_write_jpg_to_func(
            func,
            context,
            x,
            y,
            comp,
            data,
            quality);
    }

    /// <summary>
    /// From: <see cref="Api.stbi_flip_vertically_on_write(int)" />
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void FlipVerticallyOnWrite(int flip_boolean)
    {
        Api.stbi_flip_vertically_on_write(flip_boolean);
    }
}
