<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Template\ForEach.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ForEach.tt</DependentUpon>
    </None>
    <None Include="Template\QueryItem.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryItem.tt</DependentUpon>
    </None>
    <None Include="Template\QueryRefComponent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryRefComponent.tt</DependentUpon>
    </None>
    <None Include="Template\World.Query.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>World.Query.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Misaki.HighPerformance.Unsafe">
      <HintPath>..\..\Class\Misaki.HighPerformance\Misaki.HighPerformance.LowLevel\bin\Release\net9.0\Misaki.HighPerformance.LowLevel.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Template\ForEach.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ForEach.cs</LastGenOutput>
    </None>
    <None Update="Template\QueryEnumerable.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>QueryEnumerable.cs</LastGenOutput>
    </None>
    <None Update="Template\Helpers.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>Helpers.cs</LastGenOutput>
    </None>
    <None Update="Template\QueryItem.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>QueryItem.cs</LastGenOutput>
    </None>
    <None Update="Template\QueryRefComponent.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>QueryRefComponent.cs</LastGenOutput>
    </None>
    <None Update="Template\World.Query.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>World.Query.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Template\ForEach.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ForEach.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\Helpers.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Helpers.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\QueryEnumerable.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryEnumerable.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\QueryItem.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryItem.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\QueryRefComponent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryRefComponent.tt</DependentUpon>
    </Compile>
    <Compile Update="Template\World.Query.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>World.Query.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Core\Ghost.Core.csproj" />
  </ItemGroup>

</Project>
