<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release</Configurations>
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Core\Ghost.Core.csproj" />
    <ProjectReference Include="..\Ghost.Entities\Ghost.Entities.csproj" />
    <!--<ProjectReference Include="..\Ghost.Generator\Ghost.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />-->
    <ProjectReference Include="..\Ghost.Graphics\Ghost.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="ppy.SDL3-CS" Version="2026.623.0" />
  </ItemGroup>

</Project>
