<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Ghost.Editor.Core</RootNamespace>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);MVVMTK0050</NoWarn>
    <Configurations>Debug;Release;Debug_Editor;Release_Editor</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_Editor|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_Editor|ARM64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Editor|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Editor|ARM64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\MeshNode.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Controls\BasicInput\MatrixField.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MatrixField.tt</DependentUpon>
    </None>
    <None Include="Controls\BasicInput\VectorField.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VectorField.tt</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentIcons.WinUI" Version="2.1.328" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Runtime\Ghost.Core\Ghost.Core.csproj" />
    <ProjectReference Include="..\..\Runtime\Ghost.Engine\Ghost.Engine.csproj" />
    <ProjectReference Include="..\..\Runtime\Ghost.Generator\Ghost.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\ThridParty\Ghost.DXC\Ghost.DXC.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.Nvtt\Ghost.Nvtt.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.Ufbx\Ghost.Ufbx.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.StbI\Ghost.StbI.csproj" />
    <ProjectReference Include="..\Ghost.DSL\Ghost.DSL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Controls\BasicInput\MatrixField.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MatrixField.cs</LastGenOutput>
    </None>
    <None Update="Controls\BasicInput\MatrixFieldTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MatrixFieldTemplate.xaml</LastGenOutput>
    </None>
    <None Update="Controls\BasicInput\MatrixFieldTemplate.xaml">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MatrixFieldTemplate.tt</DependentUpon>
    </None>
    <None Update="Controls\BasicInput\VectorFieldTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>VectorFieldTemplate.xaml</LastGenOutput>
    </None>
    <None Update="Controls\BasicInput\ValueFieldTemplate.xaml">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValueFieldTemplate.tt</DependentUpon>
    </None>
    <None Update="Controls\BasicInput\VectorField.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>VectorField.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\BasicInput\MatrixFieldTemplate.xaml">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MatrixFieldTemplate.tt</DependentUpon>
    </Page>
    <Page Update="Controls\BasicInput\PropertyField.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Controls\BasicInput\VectorFieldTemplate.xaml">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VectorFieldTemplate.tt</DependentUpon>
    </Page>
    <Page Update="Controls\BasicInput\Vector3Field.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\BasicInput\MatrixField.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MatrixField.tt</DependentUpon>
    </Compile>
    <Compile Update="Controls\BasicInput\VectorField.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VectorField.tt</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>