<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Ghost.Editor.Core</RootNamespace>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Debug_Editor;Release_Editor</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\MeshNode.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentIcons.WinUI" Version="2.1.326" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Runtime\Ghost.Core\Ghost.Core.csproj" />
    <ProjectReference Include="..\..\Runtime\Ghost.Engine\Ghost.Engine.csproj" />
    <ProjectReference Include="..\..\Runtime\Ghost.Generator\Ghost.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\ThridParty\Ghost.DXC\Ghost.DXC.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.Nvtt\Ghost.Nvtt.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.Ufbx\Ghost.Ufbx.csproj" />
    <ProjectReference Include="..\..\ThridParty\Ghost.StbI\Ghost.StbI.csproj" />
    <ProjectReference Include="..\Ghost.DSL\Ghost.DSL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\BasicInput\PropertyField.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Controls\BasicInput\Vector3Field.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
</Project>