using Ghost.Core;
using Ghost.Core.Graphics;
namespace Ghost.DSL.ShaderCompiler.Templates;

/// <summary>
/// A single shader stage required by a template pass.
/// </summary>
public struct TemplateStage
{
    /// <summary>
    /// Path to the template HLSL file (relative to the Templates directory).
    /// </summary>
    public string templateFile;

    /// <summary>
    /// Entry point function name inside the template HLSL file.
    /// </summary>
    public string entryPoint;

    /// <summary>
    /// The DXC shader stage to compile this template as.
    /// </summary>
    public ShaderStage stage;
}

/// <summary>
/// A single pass generated by a template, composed of one or more stages.
/// </summary>
public class TemplatePassDef
{
    public string name = string.Empty;
    public PassSemantic semantic = PassSemantic.Custom;
    public PipelineSemantic pipeline = new();
    public List<TemplateStage> stages = new List<TemplateStage>();
}

/// <summary>
/// A property declared by a built-in template. These are injected
/// into the flat properties struct of every shader using the template.
/// </summary>
public class TemplatePropertyDef
{
    public TemplatePropertyDef(string type, string name, string? defaultValue = null)
    {
        this.type = type;
        this.name = name;
        this.defaultValue = defaultValue;
    }

    public string type;
    public string name;
    public string? defaultValue;
}

/// <summary>
/// Defines a built-in shader template: its base properties, the
/// payload fallback, and the passes/stages it generates.
/// </summary>
public interface IShaderTemplate
{
    /// <summary>
    /// The template name used in the DSL inheritance clause (e.g. "Unlit").
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Path to the common template HLSL file (relative to Templates directory).
    /// </summary>
    string CommonTemplateFile { get; }

    /// <summary>
    /// Base properties injected into the flat struct before user properties.
    /// </summary>
    IReadOnlyList<TemplatePropertyDef> BaseProperties { get; }

    /// <summary>
    /// Passes generated by this template.
    /// </summary>
    IReadOnlyList<TemplatePassDef> Passes { get; }

    /// <summary>
    /// HLSL defines added to every generated stage of this template.
    /// </summary>
    IReadOnlyList<string> Defines { get; }
}
