<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Combinators\**" />
    <EmbeddedResource Remove="Combinators\**" />
    <None Remove="Combinators\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Misaki.HighPerformance.Mathematics" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Core\Ghost.Core.csproj" />
  </ItemGroup>

</Project>
