<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Entities\Ghost.Entities.csproj" />
    <ProjectReference Include="..\Ghost.ArcEntities\Ghost.ArcEntities.csproj" />
    <ProjectReference Include="..\Ghost.Test.Core\Ghost.Test.Core.csproj" />
  </ItemGroup>

</Project>
