<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtime\win-x64\native\dxcompiler.dll" />
    <None Remove="runtime\win-x64\native\dxil.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="runtime\win-x64\native\dxcompiler.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="runtime\win-x64\native\dxil.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Misaki.HighPerformance.Analyzer" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Misaki.HighPerformance.Image" Version="1.0.0" />
    <PackageReference Include="TerraFX.Interop.D3D12MemoryAllocator" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
        <ProjectReference Include="../Ghost.Core/Ghost.Core.csproj" />
        <ProjectReference Include="../Ghost.Shader/Ghost.SDL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="RenderGraphModule\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Misaki.HighPerformance.LowLevel">
      <HintPath>..\..\Class\Misaki.HighPerformance\Misaki.HighPerformance.LowLevel\bin\Release\net10.0\Misaki.HighPerformance.LowLevel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
