<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="StbImageSharp" Version="2.30.15" />-->
    <PackageReference Include="Misaki.HighPerformance.Mathematics" Version="1.1.0" />
    <PackageReference Include="Vortice.Dxc.Native" Version="1.0.3" />
    <PackageReference Include="Vortice.Win32.Graphics.D3D12MemoryAllocator" Version="2.2.7" />
    <PackageReference Include="Vortice.Win32.Graphics.Direct3D.Dxc" Version="2.2.7" />
    <PackageReference Include="Vortice.Win32.Graphics.Direct3D.Fxc" Version="2.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Core\Ghost.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Misaki.HighPerformance.Image">
      <HintPath>..\..\Class\Misaki.HighPerformance\Misaki.HighPerformance.Image\bin\Release\net9.0\Misaki.HighPerformance.Image.dll</HintPath>
    </Reference>
    <Reference Include="Misaki.HighPerformance.LowLevel">
      <HintPath>..\..\Class\Misaki.HighPerformance\Misaki.HighPerformance.LowLevel\bin\Release\net9.0\Misaki.HighPerformance.LowLevel.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Win32.Apis">
      <Static>True</Static>
    </Using>
    <Using Include="Win32.Graphics.Dxgi.Apis">
      <Static>True</Static>
    </Using>
    <Using Include="Win32.Graphics.Direct3D12.Apis">
      <Static>True</Static>
    </Using>
    <Using Include="Win32.Graphics.Direct3D.Fxc.Apis">
      <Static>True</Static>
    </Using>
    <Using Include="Win32.Graphics.Direct3D.Dxc.Apis">
      <Static>True</Static>
    </Using>
  </ItemGroup>

</Project>
