<Project>
  <!--
  <PropertyGroup Condition="'$(Configuration)' == 'Debug_Editor'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;GHOST_EDITOR;GHOST_SAFETY_CHECKS</DefineConstants>
    <Optimize>false</Optimize>
    <Obfuscate>false</Obfuscate>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <TieredCompilation>false</TieredCompilation>
    <TieredPGO>false</TieredPGO>
    <PublishReadyToRun>false</PublishReadyToRun>
    <AppxPackageIncludePrivateSymbols>true</AppxPackageIncludePrivateSymbols>
  </PropertyGroup>
  -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);GHOST_SAFETY_CHECKS</DefineConstants>
  </PropertyGroup>
</Project>
