<Project>

  <PropertyGroup>
    <GhostEngineAssetDir>$(MSBuildThisFileDirectory)Runtime/Ghost.Engine/Assets</GhostEngineAssetDir>
    <GhostAssetDir Condition="'$(GhostAssetDir)' == '' and Exists('$(MSBuildProjectDirectory)\Assets')">$(MSBuildProjectDirectory)\Assets</GhostAssetDir>
    <GhostAssetDir Condition="'$(GhostAssetDir)' == ''">$(MSBuildProjectDirectory)\Asset</GhostAssetDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsGameProject)' == 'true'">
    <UpToDateCheckInput Include="$(GhostAssetDir)\**\*.*" />
    <UpToDateCheckInput Include="$(GhostEngineAssetDir)\**\*.*" />
  </ItemGroup>

  <Target Name="ComputeGhostPaths">
    <PropertyGroup>
      <GhostIntermediateOutputPath Condition="$([System.IO.Path]::IsPathRooted('$(IntermediateOutputPath)'))">$(IntermediateOutputPath)</GhostIntermediateOutputPath>
      <GhostIntermediateOutputPath Condition="'$(GhostIntermediateOutputPath)' == ''">$(MSBuildProjectDirectory)\$(IntermediateOutputPath)</GhostIntermediateOutputPath>
      <GhostAssetCacheDir Condition="'$(GhostAssetCacheDir)' == ''">$(GhostIntermediateOutputPath)AssetCache</GhostAssetCacheDir>
      <GhostAssetBuildDir Condition="'$(GhostAssetBuildDir)' == ''">$(TargetDir)Assets</GhostAssetBuildDir>
      <GhostShaderMetadataPath Condition="'$(GhostShaderMetadataPath)' == ''">$(GhostIntermediateOutputPath)shader_metadata.json</GhostShaderMetadataPath>
    </PropertyGroup>
  </Target>

  <!-- Hook Shader Metadata Extraction Tool -->
  <Target Name="GenerateShaderMetadata" 
          DependsOnTargets="ComputeGhostPaths"
          BeforeTargets="CoreCompile"
          Inputs="@(Compile)" 
          Outputs="$(GhostShaderMetadataPath)">
    
    <Message Importance="High" Text="Extracting Shader Metadata..." />
    
    <WriteLinesToFile File="$(GhostIntermediateOutputPath)compile_files.txt" Lines="@(Compile)" Overwrite="true" />
    
    <Exec Command="Ghost.ShaderMetadataTool &quot;$(GhostIntermediateOutputPath)compile_files.txt&quot; &quot;$(GhostShaderMetadataPath)&quot;" />
  </Target>

  <!-- Allow other projects to query this project's shader metadata path -->
  <Target Name="GetGhostShaderMetadataPath" Returns="$(GhostShaderMetadataPath)" DependsOnTargets="ComputeGhostPaths" />

  <!-- Hook Asset Forge CLI -->
  <Target Name="BakeAndPackAssets" 
          DependsOnTargets="ComputeGhostPaths"
          AfterTargets="Build"
          Condition="'$(IsGameProject)' == 'true'"
          Inputs="$(GhostAssetDir)\**\*.*;$(GhostEngineAssetDir)\**\*.*;$(GhostShaderMetadataPath);@(AllMetadata)"
          Outputs="$(GhostAssetBuildDir)\manifest.json">
          
    <Message Importance="High" Text="Baking and Packing Assets..." />
    
    <!-- Ask all referenced projects for their metadata files -->
    <MSBuild Projects="@(ProjectReference)" Targets="GetGhostShaderMetadataPath" SkipNonexistentTargets="true">
      <Output TaskParameter="TargetOutputs" ItemName="AllMetadata" />
    </MSBuild>
    
    <Exec Command="Ghost.AssetForge.CLI bake --asset-dir &quot;$(GhostEngineAssetDir);$(GhostAssetDir)&quot; --cache-dir &quot;$(GhostAssetCacheDir)&quot; --build-dir &quot;$(GhostAssetBuildDir)&quot; --shader-metadata &quot;$(GhostShaderMetadataPath);@(AllMetadata)&quot;" />
  </Target>

  <!-- Clean asset cache on Clean -->
  <Target Name="CleanGhostAssets" 
        BeforeTargets="Clean" 
        DependsOnTargets="ComputeGhostPaths">
    <Message Importance="High" Text="Cleaning Ghost Asset Cache and Output..." />
    <RemoveDir Directories="$(GhostAssetCacheDir)" Condition="Exists('$(GhostAssetCacheDir)')" />
  </Target>
</Project>