<Project>

  <PropertyGroup>
    <GhostEngineAssetDir>$(MSBuildThisFileDirectory)Runtime/Ghost.Engine/Assets</GhostEngineAssetDir>
    <GhostAssetDir Condition="'$(GhostAssetDir)' == '' and Exists('$(MSBuildProjectDirectory)\Assets')">$(MSBuildProjectDirectory)\Assets</GhostAssetDir>
    <GhostAssetDir Condition="'$(GhostAssetDir)' == ''">$(MSBuildProjectDirectory)\Assets</GhostAssetDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsGameProject)' == 'true'">
    <UpToDateCheckInput Include="$(GhostAssetDir)\**\*.*" />
    <UpToDateCheckInput Include="$(GhostEngineAssetDir)\**\*.*" />
  </ItemGroup>

  <Target Name="ComputeGhostPaths">
    <PropertyGroup>
      <GhostIntermediateOutputPath Condition="$([System.IO.Path]::IsPathRooted('$(IntermediateOutputPath)'))">$(IntermediateOutputPath)</GhostIntermediateOutputPath>
      <GhostIntermediateOutputPath Condition="'$(GhostIntermediateOutputPath)' == ''">$(MSBuildProjectDirectory)\$(IntermediateOutputPath)</GhostIntermediateOutputPath>
      <GhostAssetCacheDir Condition="'$(GhostAssetCacheDir)' == ''">$(GhostIntermediateOutputPath)AssetCache</GhostAssetCacheDir>
      <GhostAssetBuildDir Condition="'$(GhostAssetBuildDir)' == ''">$(TargetDir)Assets</GhostAssetBuildDir>
    </PropertyGroup>
  </Target>

  <!-- Hook Shader Metadata Extraction Tool -->
  <Target Name="GenerateShaderMetadata" 
          DependsOnTargets="ComputeGhostPaths"
          BeforeTargets="CoreCompile"
          Inputs="@(Compile)" 
          Outputs="$(GhostIntermediateOutputPath)hlsl_generated.stamp">
    
    <Message Importance="High" Text="Extracting Shader HLSL Types..." />
    
    <WriteLinesToFile File="$(GhostIntermediateOutputPath)compile_files.txt" Lines="@(Compile)" Overwrite="true" />
    
    <Exec Command="Ghost.ShaderMetadataTool &quot;$(GhostIntermediateOutputPath)compile_files.txt&quot; &quot;$(GhostAssetDir)&quot;" />
    
    <Touch Files="$(GhostIntermediateOutputPath)hlsl_generated.stamp" AlwaysCreate="true" />
  </Target>

  <!-- Hook Asset Forge CLI -->
  <Target Name="BakeAndPackAssets" 
          DependsOnTargets="ComputeGhostPaths"
          AfterTargets="Build"
          Condition="'$(IsGameProject)' == 'true'"
          Inputs="$(GhostAssetDir)\**\*.*;$(GhostEngineAssetDir)\**\*.*"
          Outputs="$(GhostAssetBuildDir)\manifest.json">
          
    <Message Importance="High" Text="Baking and Packing Assets..." />
    
    <Exec Command="Ghost.AssetForge.CLI bake --asset-dir &quot;$(GhostEngineAssetDir);$(GhostAssetDir)&quot; --cache-dir &quot;$(GhostAssetCacheDir)&quot; --build-dir &quot;$(GhostAssetBuildDir)&quot;" />
  </Target>

  <!-- Clean asset cache on Clean -->
  <Target Name="CleanGhostAssets" 
        BeforeTargets="Clean" 
        DependsOnTargets="ComputeGhostPaths">
    <Message Importance="High" Text="Cleaning Ghost Asset Cache and Output..." />
    <RemoveDir Directories="$(GhostAssetCacheDir)" Condition="Exists('$(GhostAssetCacheDir)')" />
  </Target>
</Project>