using System;

class Program {
    static void Main() {
        string definedSymbol = "__FOO_HLSL__";
        string infoName = "Foo";
        string codeBuilder = "    float4 myColor;\n";
        string fieldsBuilder = "    // fields";
        var code = $$"""
// <auto-generated/>

namespace MyNamespace
{
    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 4)]
    public partial struct {{infoName}}
    {
#if GHOST_EDITOR
        public const string HLSL_SOURCE = @"
#ifndef {{definedSymbol}}
#define {{definedSymbol}}
struct {{infoName}}
{
{{codeBuilder}}
};
#endif // {{definedSymbol}}";

{{fieldsBuilder}}
#endif
    }
}
""";
        Console.WriteLine(code);
    }
}
